#!/usr/bin/env bash
# Copyright (c) Yalochat, Inc. All rights reserved.
#
# Writes the build time values the SDK compiles with. Run it before building.

set -euo pipefail

sdk_dir="$(cd "$(dirname "$0")/.." && pwd)"
properties="$sdk_dir/local.properties"
output="$sdk_dir/Sources/YaloChatSDK/Config/BuildEnvironment.swift"

base_url="${YALO_API_BASE_URL:-}"
if [[ -z "$base_url" && -f "$properties" ]]; then
    base_url="$(sed -n 's/^yaloApiBaseUrl=//p' "$properties" | tail -n 1)"
fi

if [[ -z "$base_url" ]]; then
    cat >&2 <<MESSAGE
The Yalo API base URL is missing. Give the host and path with no scheme,
the same value the web SDK takes in VITE_YALO_API_BASE_URL. Pick one:
  ios-sdk/local.properties  yaloApiBaseUrl=example.yalochat.com/public-api-gateway
  environment               YALO_API_BASE_URL=example.yalochat.com/public-api-gateway
MESSAGE
    exit 1
fi

if [[ "$base_url" == *"://"* || "$base_url" == *'"'* || "$base_url" == *'\'* ]]; then
    echo "The Yalo API base URL must be a host and path with no scheme: $base_url" >&2
    exit 1
fi

mkdir -p "$(dirname "$output")"
cat > "$output" <<SWIFT
// Copyright (c) Yalochat, Inc. All rights reserved.
// Generated by ios-sdk/scripts/generate-build-environment.sh. Do not edit.

enum BuildEnvironment {
    static let apiBaseURL: String = "$base_url"
}
SWIFT
