import java.util.Properties
import javax.inject.Inject
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework
import com.vanniktech.maven.publish.JavadocJar
import com.vanniktech.maven.publish.KotlinMultiplatform
import com.vanniktech.maven.publish.SourcesJar

val localProps = Properties().also { props ->
    val file = rootProject.file("local.properties")
    if (file.exists()) file.inputStream().use { props.load(it) }
}

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.sqldelight)
    alias(libs.plugins.mavenPublish)
}

// The KMP Android library plugin has no BuildConfig and no build variants, so the dev-only
// toggles previously exposed as buildConfigField are generated as a plain Kotlin object.
val useFakeRepo = localProps.getProperty("yalo.useFakeRepository", "false")
    .trim().toBooleanStrictOrNull() ?: false
val transport = localProps.getProperty("yalo.transport", "WEBSOCKET").trim().uppercase()

val generateSdkBuildConfig = tasks.register("generateSdkBuildConfig") {
    val outputDir = layout.buildDirectory.dir("generated/sdkBuildConfig/kotlin")
    inputs.property("useFakeRepository", useFakeRepo)
    inputs.property("transport", transport)
    outputs.dir(outputDir)
    doLast {
        val target = outputDir.get().dir("com/yalo/chat/sdk").asFile
        target.mkdirs()
        target.resolve("SdkBuildConfig.kt").writeText(
            """
            // Copyright (c) Yalochat, Inc. All rights reserved.
            // Generated by the generateSdkBuildConfig Gradle task. Do not edit.

            package com.yalo.chat.sdk

            internal object SdkBuildConfig {
                const val USE_FAKE_REPOSITORY: Boolean = $useFakeRepo
                const val TRANSPORT: String = "$transport"
            }

            """.trimIndent()
        )
    }
}

// Stages proto/kotlin/ into the build directory, dropping the wrappers that cannot compile.
//
// GetCommandsRequestKt / GetCommandsResponseKt were generated from a newer proto revision than
// the committed SdkMessageOuterClass.java: they reference GetCommandsRequest and
// GetCommandsResponse, which that Java outer class does not declare. Compiling them fails
// outright, and their broken timestampOrNull extensions also make timestampOrNull ambiguous in
// every other proto file. The SDK does not use these wrappers; the raw Java accessors in
// SdkMessageOuterClass are sufficient. Regenerating proto/ would remove the need for this.
abstract class StageProtoSources : DefaultTask() {
    @get:InputDirectory
    abstract val source: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Inject
    abstract val fs: FileSystemOperations

    @TaskAction
    fun stage() {
        fs.sync {
            from(source)
            into(outputDir)
            exclude("**/GetCommandsRequestKt.kt", "**/GetCommandsResponseKt.kt")
        }
    }
}

val syncProtoSources = tasks.register<StageProtoSources>("syncProtoSources") {
    source.set(rootProject.file("../proto/kotlin"))
    outputDir.set(layout.buildDirectory.dir("generated/protoSources"))
}

kotlin {
    compilerOptions {
        // expect/actual classes are stable enough for use — suppress the Beta warning.
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    android {
        namespace = "com.yalo.chat.sdk"
        compileSdk = 36
        minSdk = 23

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }

        // Android resources are not processed by default with this plugin. Without this the
        // R class is never generated and src/androidMain/res is silently ignored.
        androidResources {
            enable = true
        }

        // The staged proto sources include SdkMessageOuterClass.java, so javac has to run for
        // the Android compilation.
        withJava()

        // Opt in to the androidHostTest (JVM unit test) compilation.
        withHostTest {}

        // consumerProguardFiles moved under optimization.consumerKeepRules in the new DSL.
        // Rules are silently dropped if this is not migrated.
        optimization {
            consumerKeepRules.file("consumer-proguard-rules.pro")
            consumerKeepRules.publish = true
        }

        lint {
            disable += "NullSafeMutableLiveData"
            disable += "RememberInComposition"
            disable += "FrequentlyChangingValue"
            disable += "AutoboxingStateCreation"
        }
    }

    val xcf = XCFramework("ChatSdk")
    listOf(iosArm64(), iosX64(), iosSimulatorArm64()).forEach { target ->
        target.binaries.framework {
            baseName = "ChatSdk"
            xcf.add(this)
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.client.websockets)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.ktor.client.logging)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            implementation(libs.sqldelight.coroutines.extensions)
        }

        androidMain.dependencies {
            // Proto-generated sources and lite runtime are Android/JVM-only.
            implementation(libs.protobuf.kotlin.lite)

            // OkHttp engine — required for WebSocket support (ktor-client-android uses
            // HttpURLConnection which does not implement WebSocketCapability).
            implementation(libs.ktor.client.okhttp)
            implementation(libs.sqldelight.android.driver)

            // Coroutines with Android dispatcher
            implementation(libs.coroutines.android)

            // Compose — BOM is applied via top-level dependencies block (platform() not
            // available in KMP source set blocks). Individual artifacts listed here.
            implementation(libs.compose.ui)
            implementation(libs.compose.ui.tooling.preview)
            implementation(libs.compose.material3)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material.icons.core)
            implementation(libs.compose.material.icons.extended)
            implementation(libs.activity.compose)

            // Lifecycle / ViewModel
            implementation(libs.lifecycle.viewmodel.ktx)
            implementation(libs.lifecycle.viewmodel.compose)
            implementation(libs.lifecycle.runtime.ktx)

            // Coil — async image loading (coil-network-okhttp adds the network fetcher required
            // for HTTP/HTTPS URLs; coil-compose alone only handles local files and drawables).
            implementation(libs.coil.compose)
            implementation(libs.coil.network.okhttp)

            // Keystore-backed encrypted token storage (EncryptedSharedPreferences, API 23+).
            implementation(libs.security.crypto)

            // Markdown — Compose-native CommonMark renderer for agent messages.
            implementation(libs.markdown.renderer)
            implementation(libs.markdown.renderer.m3)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
            implementation(libs.sqldelight.native.driver)
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.coroutines.test)
            implementation(libs.ktor.client.mock)
        }

        getByName("androidHostTest") {
            dependencies {
                implementation(libs.junit)
                // CIO engine required by StagingIntegrationTest (JVM-only, not available in commonTest)
                implementation(libs.ktor.client.cio)
                // JVM SQLite driver — only runs on JVM test host (Android unit tests).
                // Moved from commonTest because sqldelight-jdbc-driver has no Kotlin/Native support.
                implementation(libs.sqldelight.jdbc.driver)
            }
        }
    }

    // Proto-generated Kotlin/Java classes live in proto/kotlin/ (committed to the repo).
    // They are JVM/Android-only (protobuf-kotlin-lite has no Kotlin/Native support).
    //
    // The sources are staged through syncProtoSources rather than added directly, because the
    // AGP 9 KMP Android compilation ignores KotlinSourceSet.kotlin.filter: excludes declared
    // there are silently dropped and every file under the srcDir gets compiled. Filtering on
    // the way in is the only thing that holds.
    sourceSets.getByName("androidMain") {
        kotlin.srcDir(syncProtoSources)
        kotlin.srcDir(generateSdkBuildConfig)
    }
}

// The staged proto tree holds SdkMessageOuterClass.java. Registering it as a kotlin srcDir only
// puts it on the Kotlin java-source-roots path (enough to resolve against, but no .class is
// emitted), so it also has to be handed to javac or the compiled Kotlin wrappers would reference
// a class that is missing from the AAR.
androidComponents {
    onVariants { variant ->
        variant.sources.java?.addGeneratedSourceDirectory(syncProtoSources) { it.outputDir }
    }
}

sqldelight {
    databases {
        create("ChatDatabase") {
            packageName.set("com.yalo.chat.sdk.database")
            version = 2
        }
    }
    // Required for iOS NativeSqliteDriver — links against the system SQLite library.
    // Without this, iOS apps linking against the XCFramework get "library not found for -lsqlite3".
    linkSqlite.set(true)
}

// Restrict Compose compiler to Android only — iOS targets don't use Compose.
composeCompiler {
    targetKotlinPlatforms = setOf(KotlinPlatformType.androidJvm)
}

// Compose BOM must live here because platform() is not available inside KMP source set
// dependency blocks. The KMP Android library plugin has no build variants, so the tooling
// artifact goes on the runtime classpath instead of debugImplementation.
dependencies {
    add("androidMainImplementation", platform(libs.compose.bom))
    add("androidRuntimeClasspath", libs.compose.ui.tooling)
}

mavenPublishing {
    // AndroidSingleVariantLibrary is gone with com.android.library: this module now publishes
    // the standard KMP set (root Gradle module plus one per target).
    configure(KotlinMultiplatform(javadocJar = JavadocJar.None(), sourcesJar = SourcesJar.Sources()))
    publishToMavenCentral()
    signAllPublications()
    pom {
        name.set("Yalo Chat Android SDK")
        description.set("Jetpack Compose chat SDK for Yalo, powered by Kotlin Multiplatform")
        url.set("https://github.com/yalochat/chat-sdk")
        licenses {
            license {
                name.set("Apache-2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                id.set("yalo")
                name.set("Yalo Engineering")
                url.set("https://yalo.com")
            }
        }
        scm {
            url.set("https://github.com/yalochat/chat-sdk")
            connection.set("scm:git:git://github.com/yalochat/chat-sdk.git")
            developerConnection.set("scm:git:ssh://git@github.com/yalochat/chat-sdk.git")
        }
    }
}


