// Copyright (c) Yalochat, Inc. All rights reserved.

/** SDK layout / sizing constants. Mirrors Flutter's SdkConstants. */
export const SdkConstants = {
  iconButtonPadding: 12,
  inputBorderRadius: 25,
  rowItemSpace: 8,
  columnItemSpace: 8,
  inputPadding: 6,
  messagePadding: 16,
  quickReplyPadding: 8,
  quickReplyHeight: 48,
  appBarPreferredSize: 64,
  maxChatInputSize: 120,
  preferredWaveRecorderHeight: 48,
  defaultPageSize: 30,
  pickerButtonRadius: 12,
  imagePreviewBorderRadius: 12,
  imagePreviewIconSize: 32,
  imagePlaceHolderIconSize: 32,
  messageListPadding: 8,
  messageListMargin: 16,
  messageBorderRadius: 16,
  productPriceBorderRadius: 33,
  productPriceIconSize: 12,
  productPricePadding: 5,
  productImageBorderRadius: 2,
  collapsedListMaxItems: 3,
  soundBarsRadius: 15,
  messageWaveformWidth: 200,
  messageWaveformHeight: 40,
  titleFontSize: 18,
  cardTitleFontSize: 16,
  cardSubtitleFontSize: 14,
  statusFontSize: 12,
  statusHeight: 20,
  imageIconSize: 50,
  chatImageBorderRadius: 50,
  imageQuality: 90,
} as const;
