// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ai.yalo.chat.sdk.internal.proto.v2;

@kotlin.jvm.JvmName("-initializechatStatusRequest")
public inline fun chatStatusRequest(block: ai.yalo.chat.sdk.internal.proto.v2.ChatStatusRequestKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ChatStatusRequest =
  ai.yalo.chat.sdk.internal.proto.v2.ChatStatusRequestKt.Dsl._create(ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ChatStatusRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * ChatStatusRequest pushes a custom status string to display in the chat UI.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.ChatStatusRequest`
 */
public object ChatStatusRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ChatStatusRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ChatStatusRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ChatStatusRequest = _builder.build()

    /**
     * `string status = 1;`
     */
    public var status: kotlin.String
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * `string status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ChatStatusRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ChatStatusRequest.copy(block: `ai.yalo.chat.sdk.internal.proto.v2`.ChatStatusRequestKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ChatStatusRequest =
  `ai.yalo.chat.sdk.internal.proto.v2`.ChatStatusRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ChatStatusRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

