// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ai.yalo.chat.sdk.internal.proto.v2;

@kotlin.jvm.JvmName("-initializecustomCommandRequest")
public inline fun customCommandRequest(block: ai.yalo.chat.sdk.internal.proto.v2.CustomCommandRequestKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.CustomCommandRequest =
  ai.yalo.chat.sdk.internal.proto.v2.CustomCommandRequestKt.Dsl._create(ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.CustomCommandRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * CustomCommandRequest triggers a client-side command identified by command_id.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.CustomCommandRequest`
 */
public object CustomCommandRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.CustomCommandRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.CustomCommandRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.CustomCommandRequest = _builder.build()

    /**
     * `string command_id = 1;`
     */
    public var commandId: kotlin.String
      @kotlin.jvm.JvmName("getCommandId")
        get() = _builder.commandId
      @kotlin.jvm.JvmName("setCommandId")
        set(value) {
        _builder.commandId = value
      }
    /**
     * `string command_id = 1;`
     */
    public fun clearCommandId() {
      _builder.clearCommandId()
    }

    /**
     * `string payload = 2;`
     */
    public var payload: kotlin.String
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * `string payload = 2;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val CustomCommandRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.CustomCommandRequest.copy(block: `ai.yalo.chat.sdk.internal.proto.v2`.CustomCommandRequestKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.CustomCommandRequest =
  `ai.yalo.chat.sdk.internal.proto.v2`.CustomCommandRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.CustomCommandRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

