// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ai.yalo.chat.sdk.internal.proto.v2;

@kotlin.jvm.JvmName("-initializepollMessageItem")
public inline fun pollMessageItem(block: ai.yalo.chat.sdk.internal.proto.v2.PollMessageItemKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.PollMessageItem =
  ai.yalo.chat.sdk.internal.proto.v2.PollMessageItemKt.Dsl._create(ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.PollMessageItem.newBuilder()).apply { block() }._build()
/**
 * ```
 * PollMessageItem represents a single message entry returned by the message
 * poll endpoint. The message field reuses SdkMessage so all payload types
 * (text, image, voice, etc.) are supported without duplication.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.PollMessageItem`
 */
public object PollMessageItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.PollMessageItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.PollMessageItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.PollMessageItem = _builder.build()

    /**
     * ```
     * Server-assigned unique identifier for this poll entry.
     * ```
     *
     * `string id = 1;`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * ```
     * Server-assigned unique identifier for this poll entry.
     * ```
     *
     * `string id = 1;`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * ```
     * The SDK message payload, including its timestamp and oneof payload.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.SdkMessage message = 2;`
     */
    public var message: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.SdkMessage
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * ```
     * The SDK message payload, including its timestamp and oneof payload.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.SdkMessage message = 2;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
    /**
     * ```
     * The SDK message payload, including its timestamp and oneof payload.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.SdkMessage message = 2;`
     * @return Whether the message field is set.
     */
    public fun hasMessage(): kotlin.Boolean {
      return _builder.hasMessage()
    }

    public val PollMessageItemKt.Dsl.messageOrNull: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.SdkMessage?
      get() = _builder.messageOrNull

    /**
     * ```
     * Wall-clock time at which the message was recorded on the server.
     * ```
     *
     * `.google.protobuf.Timestamp date = 3;`
     */
    public var date: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getDate")
        get() = _builder.date
      @kotlin.jvm.JvmName("setDate")
        set(value) {
        _builder.date = value
      }
    /**
     * ```
     * Wall-clock time at which the message was recorded on the server.
     * ```
     *
     * `.google.protobuf.Timestamp date = 3;`
     */
    public fun clearDate() {
      _builder.clearDate()
    }
    /**
     * ```
     * Wall-clock time at which the message was recorded on the server.
     * ```
     *
     * `.google.protobuf.Timestamp date = 3;`
     * @return Whether the date field is set.
     */
    public fun hasDate(): kotlin.Boolean {
      return _builder.hasDate()
    }

    public val PollMessageItemKt.Dsl.dateOrNull: com.google.protobuf.Timestamp?
      get() = _builder.dateOrNull

    /**
     * ```
     * Identifier of the user associated with this message.
     * ```
     *
     * `string user_id = 4;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * ```
     * Identifier of the user associated with this message.
     * ```
     *
     * `string user_id = 4;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * ```
     * Current delivery status of the message.
     * ```
     *
     * `string status = 5;`
     */
    public var status: kotlin.String
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * ```
     * Current delivery status of the message.
     * ```
     *
     * `string status = 5;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.PollMessageItem.copy(block: `ai.yalo.chat.sdk.internal.proto.v2`.PollMessageItemKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.PollMessageItem =
  `ai.yalo.chat.sdk.internal.proto.v2`.PollMessageItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.PollMessageItemOrBuilder.messageOrNull: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.SdkMessage?
  get() = if (hasMessage()) getMessage() else null

public val ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.PollMessageItemOrBuilder.dateOrNull: com.google.protobuf.Timestamp?
  get() = if (hasDate()) getDate() else null

