// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ai.yalo.chat.sdk.internal.proto.v2;

@kotlin.jvm.JvmName("-initializeproductMessageResponse")
public inline fun productMessageResponse(block: ai.yalo.chat.sdk.internal.proto.v2.ProductMessageResponseKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ProductMessageResponse =
  ai.yalo.chat.sdk.internal.proto.v2.ProductMessageResponseKt.Dsl._create(ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ProductMessageResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * ProductMessageResponse acknowledges a ProductMessageRequest.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.ProductMessageResponse`
 */
public object ProductMessageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ProductMessageResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ProductMessageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ProductMessageResponse = _builder.build()

    /**
     * `.yalo.external_channel.in_app.sdk.v2.ResponseStatus status = 1;`
     */
    public var status: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ResponseStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v2.ResponseStatus status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ProductMessageResponseKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ProductMessageResponse.copy(block: `ai.yalo.chat.sdk.internal.proto.v2`.ProductMessageResponseKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ProductMessageResponse =
  `ai.yalo.chat.sdk.internal.proto.v2`.ProductMessageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.ProductMessageResponseOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

