// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package ai.yalo.chat.sdk.internal.proto.v2;

@kotlin.jvm.JvmName("-initializevideoMessage")
public inline fun videoMessage(block: ai.yalo.chat.sdk.internal.proto.v2.VideoMessageKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.VideoMessage =
  ai.yalo.chat.sdk.internal.proto.v2.VideoMessageKt.Dsl._create(ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.VideoMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * VideoMessage holds the payload of a video conversation turn.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.VideoMessage`
 */
public object VideoMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.VideoMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.VideoMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.VideoMessage = _builder.build()

    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val VideoMessageKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * `optional string text = 2;`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `optional string text = 2;`
     */
    public fun clearText() {
      _builder.clearText()
    }
    /**
     * `optional string text = 2;`
     * @return Whether the text field is set.
     */
    public fun hasText(): kotlin.Boolean {
      return _builder.hasText()
    }

    /**
     * `string media_url = 3;`
     */
    public var mediaUrl: kotlin.String
      @kotlin.jvm.JvmName("getMediaUrl")
        get() = _builder.mediaUrl
      @kotlin.jvm.JvmName("setMediaUrl")
        set(value) {
        _builder.mediaUrl = value
      }
    /**
     * `string media_url = 3;`
     */
    public fun clearMediaUrl() {
      _builder.clearMediaUrl()
    }

    /**
     * `string media_type = 4;`
     */
    public var mediaType: kotlin.String
      @kotlin.jvm.JvmName("getMediaType")
        get() = _builder.mediaType
      @kotlin.jvm.JvmName("setMediaType")
        set(value) {
        _builder.mediaType = value
      }
    /**
     * `string media_type = 4;`
     */
    public fun clearMediaType() {
      _builder.clearMediaType()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v2.MessageStatus status = 5;`
     */
    public var status: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.MessageStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v2.MessageStatus status = 5;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v2.MessageRole role = 6;`
     */
    public var role: ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.MessageRole
      @kotlin.jvm.JvmName("getRole")
        get() = _builder.role
      @kotlin.jvm.JvmName("setRole")
        set(value) {
        _builder.role = value
      }
    public var roleValue: kotlin.Int
      @kotlin.jvm.JvmName("getRoleValue")
        get() = _builder.roleValue
      @kotlin.jvm.JvmName("setRoleValue")
        set(value) {
        _builder.roleValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v2.MessageRole role = 6;`
     */
    public fun clearRole() {
      _builder.clearRole()
    }

    /**
     * `int64 byte_count = 7;`
     */
    public var byteCount: kotlin.Long
      @kotlin.jvm.JvmName("getByteCount")
        get() = _builder.byteCount
      @kotlin.jvm.JvmName("setByteCount")
        set(value) {
        _builder.byteCount = value
      }
    /**
     * `int64 byte_count = 7;`
     */
    public fun clearByteCount() {
      _builder.clearByteCount()
    }

    /**
     * `string file_name = 8;`
     */
    public var fileName: kotlin.String
      @kotlin.jvm.JvmName("getFileName")
        get() = _builder.fileName
      @kotlin.jvm.JvmName("setFileName")
        set(value) {
        _builder.fileName = value
      }
    /**
     * `string file_name = 8;`
     */
    public fun clearFileName() {
      _builder.clearFileName()
    }

    /**
     * `double duration = 9;`
     */
    public var duration: kotlin.Double
      @kotlin.jvm.JvmName("getDuration")
        get() = _builder.duration
      @kotlin.jvm.JvmName("setDuration")
        set(value) {
        _builder.duration = value
      }
    /**
     * `double duration = 9;`
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.VideoMessage.copy(block: `ai.yalo.chat.sdk.internal.proto.v2`.VideoMessageKt.Dsl.() -> kotlin.Unit): ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.VideoMessage =
  `ai.yalo.chat.sdk.internal.proto.v2`.VideoMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val ai.yalo.chat.sdk.internal.proto.v2.SdkMessageOuterClass.VideoMessageOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

