// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializeauthRequest")
public inline fun authRequest(block: yalo.external_channel.in_app.sdk.v1.AuthRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AuthRequest =
  yalo.external_channel.in_app.sdk.v1.AuthRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AuthRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * AuthRequest is the body of POST /auth used to obtain an initial access token.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.AuthRequest`
 */
public object AuthRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AuthRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AuthRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AuthRequest = _builder.build()

    /**
     * `string user_type = 1;`
     */
    public var userType: kotlin.String
      @kotlin.jvm.JvmName("getUserType")
        get() = _builder.userType
      @kotlin.jvm.JvmName("setUserType")
        set(value) {
        _builder.userType = value
      }
    /**
     * `string user_type = 1;`
     */
    public fun clearUserType() {
      _builder.clearUserType()
    }

    /**
     * `string channel_id = 2;`
     */
    public var channelId: kotlin.String
      @kotlin.jvm.JvmName("getChannelId")
        get() = _builder.channelId
      @kotlin.jvm.JvmName("setChannelId")
        set(value) {
        _builder.channelId = value
      }
    /**
     * `string channel_id = 2;`
     */
    public fun clearChannelId() {
      _builder.clearChannelId()
    }

    /**
     * `string organization_id = 3;`
     */
    public var organizationId: kotlin.String
      @kotlin.jvm.JvmName("getOrganizationId")
        get() = _builder.organizationId
      @kotlin.jvm.JvmName("setOrganizationId")
        set(value) {
        _builder.organizationId = value
      }
    /**
     * `string organization_id = 3;`
     */
    public fun clearOrganizationId() {
      _builder.clearOrganizationId()
    }

    /**
     * ```
     * Unix timestamp in seconds.
     * ```
     *
     * `int64 timestamp = 4;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * ```
     * Unix timestamp in seconds.
     * ```
     *
     * `int64 timestamp = 4;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AuthRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.AuthRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AuthRequest =
  `yalo.external_channel.in_app.sdk.v1`.AuthRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

