// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializebutton")
public inline fun button(block: yalo.external_channel.in_app.sdk.v1.ButtonKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Button =
  yalo.external_channel.in_app.sdk.v1.ButtonKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Button.newBuilder()).apply { block() }._build()
/**
 * ```
 * Button represents a single tappable option attached to a message.
 * url is required when button_type is BUTTON_TYPE_LINK and ignored otherwise.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.Button`
 */
public object ButtonKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Button.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Button.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Button = _builder.build()

    /**
     * `string text = 1;`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ButtonType button_type = 2;`
     */
    public var buttonType: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ButtonType
      @kotlin.jvm.JvmName("getButtonType")
        get() = _builder.buttonType
      @kotlin.jvm.JvmName("setButtonType")
        set(value) {
        _builder.buttonType = value
      }
    public var buttonTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getButtonTypeValue")
        get() = _builder.buttonTypeValue
      @kotlin.jvm.JvmName("setButtonTypeValue")
        set(value) {
        _builder.buttonTypeValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ButtonType button_type = 2;`
     */
    public fun clearButtonType() {
      _builder.clearButtonType()
    }

    /**
     * `optional string url = 3;`
     */
    public var url: kotlin.String
      @kotlin.jvm.JvmName("getUrl")
        get() = _builder.url
      @kotlin.jvm.JvmName("setUrl")
        set(value) {
        _builder.url = value
      }
    /**
     * `optional string url = 3;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }
    /**
     * `optional string url = 3;`
     * @return Whether the url field is set.
     */
    public fun hasUrl(): kotlin.Boolean {
      return _builder.hasUrl()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Button.copy(block: `yalo.external_channel.in_app.sdk.v1`.ButtonKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Button =
  `yalo.external_channel.in_app.sdk.v1`.ButtonKt.Dsl._create(this.toBuilder()).apply { block() }._build()

