// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializecTAButton")
public inline fun cTAButton(block: yalo.external_channel.in_app.sdk.v1.CTAButtonKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton =
  yalo.external_channel.in_app.sdk.v1.CTAButtonKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton.newBuilder()).apply { block() }._build()
/**
 * ```
 * CTAButton represents a single call-to-action link button.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.CTAButton`
 */
public object CTAButtonKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton = _builder.build()

    /**
     * `string text = 1;`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `string text = 1;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * `string url = 2;`
     */
    public var url: kotlin.String
      @kotlin.jvm.JvmName("getUrl")
        get() = _builder.url
      @kotlin.jvm.JvmName("setUrl")
        set(value) {
        _builder.url = value
      }
    /**
     * `string url = 2;`
     */
    public fun clearUrl() {
      _builder.clearUrl()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton.copy(block: `yalo.external_channel.in_app.sdk.v1`.CTAButtonKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton =
  `yalo.external_channel.in_app.sdk.v1`.CTAButtonKt.Dsl._create(this.toBuilder()).apply { block() }._build()

