// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializecTAMessageRequest")
public inline fun cTAMessageRequest(block: yalo.external_channel.in_app.sdk.v1.CTAMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequest =
  yalo.external_channel.in_app.sdk.v1.CTAMessageRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * CTAMessageRequest delivers a set of link buttons to the client UI.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.CTAMessageRequest`
 */
public object CTAMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequest = _builder.build()

    /**
     * `.yalo.external_channel.in_app.sdk.v1.CTAMessage content = 1;`
     */
    public var content: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CTAMessage content = 1;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CTAMessage content = 1;`
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }

    public val CTAMessageRequestKt.Dsl.contentOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage?
      get() = _builder.contentOrNull

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val CTAMessageRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.CTAMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequest =
  `yalo.external_channel.in_app.sdk.v1`.CTAMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequestOrBuilder.contentOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage?
  get() = if (hasContent()) getContent() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

