// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializecTAMessage")
public inline fun cTAMessage(block: yalo.external_channel.in_app.sdk.v1.CTAMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage =
  yalo.external_channel.in_app.sdk.v1.CTAMessageKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * CTAMessage holds the content of a CTA message.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.CTAMessage`
 */
public object CTAMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage = _builder.build()

    /**
     * `string header = 1;`
     */
    public var header: kotlin.String
      @kotlin.jvm.JvmName("getHeader")
        get() = _builder.header
      @kotlin.jvm.JvmName("setHeader")
        set(value) {
        _builder.header = value
      }
    /**
     * `string header = 1;`
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }

    /**
     * `string body = 2;`
     */
    public var body: kotlin.String
      @kotlin.jvm.JvmName("getBody")
        get() = _builder.body
      @kotlin.jvm.JvmName("setBody")
        set(value) {
        _builder.body = value
      }
    /**
     * `string body = 2;`
     */
    public fun clearBody() {
      _builder.clearBody()
    }

    /**
     * `string footer = 3;`
     */
    public var footer: kotlin.String
      @kotlin.jvm.JvmName("getFooter")
        get() = _builder.footer
      @kotlin.jvm.JvmName("setFooter")
        set(value) {
        _builder.footer = value
      }
    /**
     * `string footer = 3;`
     */
    public fun clearFooter() {
      _builder.clearFooter()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ButtonsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * At least one CTA button must be provided.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v1.CTAButton buttons = 4;`
     */
     public val buttons: com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton, ButtonsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.buttonsList
      )
    /**
     * ```
     * At least one CTA button must be provided.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v1.CTAButton buttons = 4;`
     * @param value The buttons to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addButtons")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton, ButtonsProxy>.add(value: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton) {
      _builder.addButtons(value)
    }
    /**
     * ```
     * At least one CTA button must be provided.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v1.CTAButton buttons = 4;`
     * @param value The buttons to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignButtons")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton, ButtonsProxy>.plusAssign(value: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton) {
      add(value)
    }
    /**
     * ```
     * At least one CTA button must be provided.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v1.CTAButton buttons = 4;`
     * @param values The buttons to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllButtons")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton, ButtonsProxy>.addAll(values: kotlin.collections.Iterable<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton>) {
      _builder.addAllButtons(values)
    }
    /**
     * ```
     * At least one CTA button must be provided.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v1.CTAButton buttons = 4;`
     * @param values The buttons to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllButtons")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton, ButtonsProxy>.plusAssign(values: kotlin.collections.Iterable<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton>) {
      addAll(values)
    }
    /**
     * ```
     * At least one CTA button must be provided.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v1.CTAButton buttons = 4;`
     * @param index The index to set the value at.
     * @param value The buttons to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setButtons")
    public operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton, ButtonsProxy>.set(index: kotlin.Int, value: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton) {
      _builder.setButtons(index, value)
    }
    /**
     * ```
     * At least one CTA button must be provided.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v1.CTAButton buttons = 4;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearButtons")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAButton, ButtonsProxy>.clear() {
      _builder.clearButtons()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage.copy(block: `yalo.external_channel.in_app.sdk.v1`.CTAMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessage =
  `yalo.external_channel.in_app.sdk.v1`.CTAMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

