// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializegetCommandsRequest")
public inline fun getCommandsRequest(block: yalo.external_channel.in_app.sdk.v1.GetCommandsRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsRequest =
  yalo.external_channel.in_app.sdk.v1.GetCommandsRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * GetCommandsRequest is sent by the client to declare that it is ready to
 * receive the list of commands it is able to execute. The body is intentionally empty.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.GetCommandsRequest`
 */
public object GetCommandsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsRequest = _builder.build()
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.GetCommandsRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsRequest =
  `yalo.external_channel.in_app.sdk.v1`.GetCommandsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

