// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializeguidanceCardRequest")
public inline fun guidanceCardRequest(block: yalo.external_channel.in_app.sdk.v1.GuidanceCardRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest =
  yalo.external_channel.in_app.sdk.v1.GuidanceCardRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * GuidanceCardRequest asks the channel to return the current guidance cards.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.GuidanceCardRequest`
 */
public object GuidanceCardRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest = _builder.build()

    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val GuidanceCardRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * ```
     * Identifies the target entity for which guidance cards are requested.
     * ```
     *
     * `optional string target_id = 2;`
     */
    public var targetId: kotlin.String
      @kotlin.jvm.JvmName("getTargetId")
        get() = _builder.targetId
      @kotlin.jvm.JvmName("setTargetId")
        set(value) {
        _builder.targetId = value
      }
    /**
     * ```
     * Identifies the target entity for which guidance cards are requested.
     * ```
     *
     * `optional string target_id = 2;`
     */
    public fun clearTargetId() {
      _builder.clearTargetId()
    }
    /**
     * ```
     * Identifies the target entity for which guidance cards are requested.
     * ```
     *
     * `optional string target_id = 2;`
     * @return Whether the targetId field is set.
     */
    public fun hasTargetId(): kotlin.Boolean {
      return _builder.hasTargetId()
    }

    /**
     * ```
     * Additional context for the guidance card lookup.
     * ```
     *
     * `optional string context = 3;`
     */
    public var context: kotlin.String
      @kotlin.jvm.JvmName("getContext")
        get() = _builder.context
      @kotlin.jvm.JvmName("setContext")
        set(value) {
        _builder.context = value
      }
    /**
     * ```
     * Additional context for the guidance card lookup.
     * ```
     *
     * `optional string context = 3;`
     */
    public fun clearContext() {
      _builder.clearContext()
    }
    /**
     * ```
     * Additional context for the guidance card lookup.
     * ```
     *
     * `optional string context = 3;`
     * @return Whether the context field is set.
     */
    public fun hasContext(): kotlin.Boolean {
      return _builder.hasContext()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.GuidanceCardRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest =
  `yalo.external_channel.in_app.sdk.v1`.GuidanceCardRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

