// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializeimageMessage")
public inline fun imageMessage(block: yalo.external_channel.in_app.sdk.v1.ImageMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessage =
  yalo.external_channel.in_app.sdk.v1.ImageMessageKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * ImageMessage holds the payload of an image conversation turn.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.ImageMessage`
 */
public object ImageMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessage = _builder.build()

    /**
     * `optional string message_id = 1;`
     */
    public var messageId: kotlin.String
      @kotlin.jvm.JvmName("getMessageId")
        get() = _builder.messageId
      @kotlin.jvm.JvmName("setMessageId")
        set(value) {
        _builder.messageId = value
      }
    /**
     * `optional string message_id = 1;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }
    /**
     * `optional string message_id = 1;`
     * @return Whether the messageId field is set.
     */
    public fun hasMessageId(): kotlin.Boolean {
      return _builder.hasMessageId()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ImageMessageKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * `optional string text = 3;`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `optional string text = 3;`
     */
    public fun clearText() {
      _builder.clearText()
    }
    /**
     * `optional string text = 3;`
     * @return Whether the text field is set.
     */
    public fun hasText(): kotlin.Boolean {
      return _builder.hasText()
    }

    /**
     * `string media_url = 4;`
     */
    public var mediaUrl: kotlin.String
      @kotlin.jvm.JvmName("getMediaUrl")
        get() = _builder.mediaUrl
      @kotlin.jvm.JvmName("setMediaUrl")
        set(value) {
        _builder.mediaUrl = value
      }
    /**
     * `string media_url = 4;`
     */
    public fun clearMediaUrl() {
      _builder.clearMediaUrl()
    }

    /**
     * `string media_type = 5;`
     */
    public var mediaType: kotlin.String
      @kotlin.jvm.JvmName("getMediaType")
        get() = _builder.mediaType
      @kotlin.jvm.JvmName("setMediaType")
        set(value) {
        _builder.mediaType = value
      }
    /**
     * `string media_type = 5;`
     */
    public fun clearMediaType() {
      _builder.clearMediaType()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageStatus status = 6;`
     */
    public var status: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageStatus status = 6;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageRole role = 7;`
     */
    public var role: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageRole
      @kotlin.jvm.JvmName("getRole")
        get() = _builder.role
      @kotlin.jvm.JvmName("setRole")
        set(value) {
        _builder.role = value
      }
    public var roleValue: kotlin.Int
      @kotlin.jvm.JvmName("getRoleValue")
        get() = _builder.roleValue
      @kotlin.jvm.JvmName("setRoleValue")
        set(value) {
        _builder.roleValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageRole role = 7;`
     */
    public fun clearRole() {
      _builder.clearRole()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessage.copy(block: `yalo.external_channel.in_app.sdk.v1`.ImageMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessage =
  `yalo.external_channel.in_app.sdk.v1`.ImageMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessageOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

