// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializemessageReceiptRequest")
public inline fun messageReceiptRequest(block: yalo.external_channel.in_app.sdk.v1.MessageReceiptRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest =
  yalo.external_channel.in_app.sdk.v1.MessageReceiptRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * MessageReceiptRequest notifies the other party of a message status change.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.MessageReceiptRequest`
 */
public object MessageReceiptRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest = _builder.build()

    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageStatus status = 1;`
     */
    public var status: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageStatus status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `string message_id = 2;`
     */
    public var messageId: kotlin.String
      @kotlin.jvm.JvmName("getMessageId")
        get() = _builder.messageId
      @kotlin.jvm.JvmName("setMessageId")
        set(value) {
        _builder.messageId = value
      }
    /**
     * `string message_id = 2;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val MessageReceiptRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class QuickRepliesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string quick_replies = 4;`
     * @return A list containing the quickReplies.
     */
    public val quickReplies: com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.quickRepliesList
      )
    /**
     * `repeated string quick_replies = 4;`
     * @param value The quickReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addQuickReplies")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.add(value: kotlin.String) {
      _builder.addQuickReplies(value)
    }
    /**
     * `repeated string quick_replies = 4;`
     * @param value The quickReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignQuickReplies")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string quick_replies = 4;`
     * @param values The quickReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllQuickReplies")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllQuickReplies(values)
    }
    /**
     * `repeated string quick_replies = 4;`
     * @param values The quickReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllQuickReplies")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string quick_replies = 4;`
     * @param index The index to set the value at.
     * @param value The quickReplies to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setQuickReplies")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setQuickReplies(index, value)
    }/**
     * `repeated string quick_replies = 4;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setQuickReplies")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.clear() {
      _builder.clearQuickReplies()
    }}
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.MessageReceiptRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest =
  `yalo.external_channel.in_app.sdk.v1`.MessageReceiptRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

