// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializeproductMessageRequest")
public inline fun productMessageRequest(block: yalo.external_channel.in_app.sdk.v1.ProductMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest =
  yalo.external_channel.in_app.sdk.v1.ProductMessageRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * ProductMessageRequest delivers a list of products rendered as a vertical list or horizontal carousel.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.ProductMessageRequest`
 */
public object ProductMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ProductsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .yalo.external_channel.in_app.sdk.v1.Product products = 1;`
     */
     public val products: com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product, ProductsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.productsList
      )
    /**
     * `repeated .yalo.external_channel.in_app.sdk.v1.Product products = 1;`
     * @param value The products to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addProducts")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product, ProductsProxy>.add(value: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product) {
      _builder.addProducts(value)
    }
    /**
     * `repeated .yalo.external_channel.in_app.sdk.v1.Product products = 1;`
     * @param value The products to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignProducts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product, ProductsProxy>.plusAssign(value: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product) {
      add(value)
    }
    /**
     * `repeated .yalo.external_channel.in_app.sdk.v1.Product products = 1;`
     * @param values The products to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllProducts")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product, ProductsProxy>.addAll(values: kotlin.collections.Iterable<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product>) {
      _builder.addAllProducts(values)
    }
    /**
     * `repeated .yalo.external_channel.in_app.sdk.v1.Product products = 1;`
     * @param values The products to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllProducts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product, ProductsProxy>.plusAssign(values: kotlin.collections.Iterable<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product>) {
      addAll(values)
    }
    /**
     * `repeated .yalo.external_channel.in_app.sdk.v1.Product products = 1;`
     * @param index The index to set the value at.
     * @param value The products to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setProducts")
    public operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product, ProductsProxy>.set(index: kotlin.Int, value: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product) {
      _builder.setProducts(index, value)
    }
    /**
     * `repeated .yalo.external_channel.in_app.sdk.v1.Product products = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearProducts")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.Product, ProductsProxy>.clear() {
      _builder.clearProducts()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageRequest.Orientation orientation = 2;`
     */
    public var orientation: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest.Orientation
      @kotlin.jvm.JvmName("getOrientation")
        get() = _builder.orientation
      @kotlin.jvm.JvmName("setOrientation")
        set(value) {
        _builder.orientation = value
      }
    public var orientationValue: kotlin.Int
      @kotlin.jvm.JvmName("getOrientationValue")
        get() = _builder.orientationValue
      @kotlin.jvm.JvmName("setOrientationValue")
        set(value) {
        _builder.orientationValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageRequest.Orientation orientation = 2;`
     */
    public fun clearOrientation() {
      _builder.clearOrientation()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ProductMessageRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.ProductMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest =
  `yalo.external_channel.in_app.sdk.v1`.ProductMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

