// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializepromotionMessageRequest")
public inline fun promotionMessageRequest(block: yalo.external_channel.in_app.sdk.v1.PromotionMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest =
  yalo.external_channel.in_app.sdk.v1.PromotionMessageRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * PromotionMessageRequest delivers a promotional offer to the client UI.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.PromotionMessageRequest`
 */
public object PromotionMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest = _builder.build()

    /**
     * `string promotion_id = 1;`
     */
    public var promotionId: kotlin.String
      @kotlin.jvm.JvmName("getPromotionId")
        get() = _builder.promotionId
      @kotlin.jvm.JvmName("setPromotionId")
        set(value) {
        _builder.promotionId = value
      }
    /**
     * `string promotion_id = 1;`
     */
    public fun clearPromotionId() {
      _builder.clearPromotionId()
    }

    /**
     * `string title = 2;`
     */
    public var title: kotlin.String
      @kotlin.jvm.JvmName("getTitle")
        get() = _builder.title
      @kotlin.jvm.JvmName("setTitle")
        set(value) {
        _builder.title = value
      }
    /**
     * `string title = 2;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * `string gain = 3;`
     */
    public var gain: kotlin.String
      @kotlin.jvm.JvmName("getGain")
        get() = _builder.gain
      @kotlin.jvm.JvmName("setGain")
        set(value) {
        _builder.gain = value
      }
    /**
     * `string gain = 3;`
     */
    public fun clearGain() {
      _builder.clearGain()
    }

    /**
     * `string description = 4;`
     */
    public var description: kotlin.String
      @kotlin.jvm.JvmName("getDescription")
        get() = _builder.description
      @kotlin.jvm.JvmName("setDescription")
        set(value) {
        _builder.description = value
      }
    /**
     * `string description = 4;`
     */
    public fun clearDescription() {
      _builder.clearDescription()
    }

    /**
     * `string image_url = 5;`
     */
    public var imageUrl: kotlin.String
      @kotlin.jvm.JvmName("getImageUrl")
        get() = _builder.imageUrl
      @kotlin.jvm.JvmName("setImageUrl")
        set(value) {
        _builder.imageUrl = value
      }
    /**
     * `string image_url = 5;`
     */
    public fun clearImageUrl() {
      _builder.clearImageUrl()
    }

    /**
     * `string footer = 6;`
     */
    public var footer: kotlin.String
      @kotlin.jvm.JvmName("getFooter")
        get() = _builder.footer
      @kotlin.jvm.JvmName("setFooter")
        set(value) {
        _builder.footer = value
      }
    /**
     * `string footer = 6;`
     */
    public fun clearFooter() {
      _builder.clearFooter()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 7;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 7;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 7;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val PromotionMessageRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.PromotionMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest =
  `yalo.external_channel.in_app.sdk.v1`.PromotionMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

