// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializerefreshTokenRequest")
public inline fun refreshTokenRequest(block: yalo.external_channel.in_app.sdk.v1.RefreshTokenRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RefreshTokenRequest =
  yalo.external_channel.in_app.sdk.v1.RefreshTokenRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RefreshTokenRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * RefreshTokenRequest is the body of POST /oauth/token used to refresh an
 * expired access token via the refresh_token grant.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.RefreshTokenRequest`
 */
public object RefreshTokenRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RefreshTokenRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RefreshTokenRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RefreshTokenRequest = _builder.build()

    /**
     * `string grant_type = 1;`
     */
    public var grantType: kotlin.String
      @kotlin.jvm.JvmName("getGrantType")
        get() = _builder.grantType
      @kotlin.jvm.JvmName("setGrantType")
        set(value) {
        _builder.grantType = value
      }
    /**
     * `string grant_type = 1;`
     */
    public fun clearGrantType() {
      _builder.clearGrantType()
    }

    /**
     * `string refresh_token = 2;`
     */
    public var refreshToken: kotlin.String
      @kotlin.jvm.JvmName("getRefreshToken")
        get() = _builder.refreshToken
      @kotlin.jvm.JvmName("setRefreshToken")
        set(value) {
        _builder.refreshToken = value
      }
    /**
     * `string refresh_token = 2;`
     */
    public fun clearRefreshToken() {
      _builder.clearRefreshToken()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RefreshTokenRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.RefreshTokenRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RefreshTokenRequest =
  `yalo.external_channel.in_app.sdk.v1`.RefreshTokenRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

