// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializeremoveFromCartRequest")
public inline fun removeFromCartRequest(block: yalo.external_channel.in_app.sdk.v1.RemoveFromCartRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest =
  yalo.external_channel.in_app.sdk.v1.RemoveFromCartRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * RemoveFromCartRequest asks the channel to remove a SKU from the active cart.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.RemoveFromCartRequest`
 */
public object RemoveFromCartRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest = _builder.build()

    /**
     * `string sku = 1;`
     */
    public var sku: kotlin.String
      @kotlin.jvm.JvmName("getSku")
        get() = _builder.sku
      @kotlin.jvm.JvmName("setSku")
        set(value) {
        _builder.sku = value
      }
    /**
     * `string sku = 1;`
     */
    public fun clearSku() {
      _builder.clearSku()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val RemoveFromCartRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * ```
     * If omitted the entire SKU line is removed from the cart.
     * ```
     *
     * `optional double quantity = 3;`
     */
    public var quantity: kotlin.Double
      @kotlin.jvm.JvmName("getQuantity")
        get() = _builder.quantity
      @kotlin.jvm.JvmName("setQuantity")
        set(value) {
        _builder.quantity = value
      }
    /**
     * ```
     * If omitted the entire SKU line is removed from the cart.
     * ```
     *
     * `optional double quantity = 3;`
     */
    public fun clearQuantity() {
      _builder.clearQuantity()
    }
    /**
     * ```
     * If omitted the entire SKU line is removed from the cart.
     * ```
     *
     * `optional double quantity = 3;`
     * @return Whether the quantity field is set.
     */
    public fun hasQuantity(): kotlin.Boolean {
      return _builder.hasQuantity()
    }

    /**
     * ```
     * Whether the quantity refers to primary units or subunits.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.UnitType unit_type = 4;`
     */
    public var unitType: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.UnitType
      @kotlin.jvm.JvmName("getUnitType")
        get() = _builder.unitType
      @kotlin.jvm.JvmName("setUnitType")
        set(value) {
        _builder.unitType = value
      }
    public var unitTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getUnitTypeValue")
        get() = _builder.unitTypeValue
      @kotlin.jvm.JvmName("setUnitTypeValue")
        set(value) {
        _builder.unitTypeValue = value
      }
    /**
     * ```
     * Whether the quantity refers to primary units or subunits.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.UnitType unit_type = 4;`
     */
    public fun clearUnitType() {
      _builder.clearUnitType()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.RemoveFromCartRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest =
  `yalo.external_channel.in_app.sdk.v1`.RemoveFromCartRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

