// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializesdkMessage")
public inline fun sdkMessage(block: yalo.external_channel.in_app.sdk.v1.SdkMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage =
  yalo.external_channel.in_app.sdk.v1.SdkMessageKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * SdkMessage is the top-level wrapper sent over the bidirectional stream.
 * Exactly one payload field is set per message; the oneof lets the Go runtime
 * expose a type-switch-friendly isSdkMessage_Payload interface.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.SdkMessage`
 */
public object SdkMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage = _builder.build()

    /**
     * ```
     * A client-generated id that can be used to correlate requests with responses.
     * ```
     *
     * `string correlation_id = 1;`
     */
    public var correlationId: kotlin.String
      @kotlin.jvm.JvmName("getCorrelationId")
        get() = _builder.correlationId
      @kotlin.jvm.JvmName("setCorrelationId")
        set(value) {
        _builder.correlationId = value
      }
    /**
     * ```
     * A client-generated id that can be used to correlate requests with responses.
     * ```
     *
     * `string correlation_id = 1;`
     */
    public fun clearCorrelationId() {
      _builder.clearCorrelationId()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val SdkMessageKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * ```
     * Bi-directional
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.TextMessageRequest text_message_request = 10;`
     */
    public var textMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.TextMessageRequest
      @kotlin.jvm.JvmName("getTextMessageRequest")
        get() = _builder.textMessageRequest
      @kotlin.jvm.JvmName("setTextMessageRequest")
        set(value) {
        _builder.textMessageRequest = value
      }
    /**
     * ```
     * Bi-directional
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.TextMessageRequest text_message_request = 10;`
     */
    public fun clearTextMessageRequest() {
      _builder.clearTextMessageRequest()
    }
    /**
     * ```
     * Bi-directional
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.TextMessageRequest text_message_request = 10;`
     * @return Whether the textMessageRequest field is set.
     */
    public fun hasTextMessageRequest(): kotlin.Boolean {
      return _builder.hasTextMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.VoiceNoteMessageRequest voice_note_message_request = 12;`
     */
    public var voiceNoteMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceNoteMessageRequest
      @kotlin.jvm.JvmName("getVoiceNoteMessageRequest")
        get() = _builder.voiceNoteMessageRequest
      @kotlin.jvm.JvmName("setVoiceNoteMessageRequest")
        set(value) {
        _builder.voiceNoteMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VoiceNoteMessageRequest voice_note_message_request = 12;`
     */
    public fun clearVoiceNoteMessageRequest() {
      _builder.clearVoiceNoteMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VoiceNoteMessageRequest voice_note_message_request = 12;`
     * @return Whether the voiceNoteMessageRequest field is set.
     */
    public fun hasVoiceNoteMessageRequest(): kotlin.Boolean {
      return _builder.hasVoiceNoteMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ImageMessageRequest image_message_request = 14;`
     */
    public var imageMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessageRequest
      @kotlin.jvm.JvmName("getImageMessageRequest")
        get() = _builder.imageMessageRequest
      @kotlin.jvm.JvmName("setImageMessageRequest")
        set(value) {
        _builder.imageMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ImageMessageRequest image_message_request = 14;`
     */
    public fun clearImageMessageRequest() {
      _builder.clearImageMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ImageMessageRequest image_message_request = 14;`
     * @return Whether the imageMessageRequest field is set.
     */
    public fun hasImageMessageRequest(): kotlin.Boolean {
      return _builder.hasImageMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageReceiptRequest message_receipt_request = 16;`
     */
    public var messageReceiptRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest
      @kotlin.jvm.JvmName("getMessageReceiptRequest")
        get() = _builder.messageReceiptRequest
      @kotlin.jvm.JvmName("setMessageReceiptRequest")
        set(value) {
        _builder.messageReceiptRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageReceiptRequest message_receipt_request = 16;`
     */
    public fun clearMessageReceiptRequest() {
      _builder.clearMessageReceiptRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageReceiptRequest message_receipt_request = 16;`
     * @return Whether the messageReceiptRequest field is set.
     */
    public fun hasMessageReceiptRequest(): kotlin.Boolean {
      return _builder.hasMessageReceiptRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.AttachmentMessageRequest attachment_message_request = 18;`
     */
    public var attachmentMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AttachmentMessageRequest
      @kotlin.jvm.JvmName("getAttachmentMessageRequest")
        get() = _builder.attachmentMessageRequest
      @kotlin.jvm.JvmName("setAttachmentMessageRequest")
        set(value) {
        _builder.attachmentMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AttachmentMessageRequest attachment_message_request = 18;`
     */
    public fun clearAttachmentMessageRequest() {
      _builder.clearAttachmentMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AttachmentMessageRequest attachment_message_request = 18;`
     * @return Whether the attachmentMessageRequest field is set.
     */
    public fun hasAttachmentMessageRequest(): kotlin.Boolean {
      return _builder.hasAttachmentMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessageRequest video_message_request = 38;`
     */
    public var videoMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest
      @kotlin.jvm.JvmName("getVideoMessageRequest")
        get() = _builder.videoMessageRequest
      @kotlin.jvm.JvmName("setVideoMessageRequest")
        set(value) {
        _builder.videoMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessageRequest video_message_request = 38;`
     */
    public fun clearVideoMessageRequest() {
      _builder.clearVideoMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessageRequest video_message_request = 38;`
     * @return Whether the videoMessageRequest field is set.
     */
    public fun hasVideoMessageRequest(): kotlin.Boolean {
      return _builder.hasVideoMessageRequest()
    }

    /**
     * ```
     * Client → channel
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartRequest add_to_cart_request = 20;`
     */
    public var addToCartRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddToCartRequest
      @kotlin.jvm.JvmName("getAddToCartRequest")
        get() = _builder.addToCartRequest
      @kotlin.jvm.JvmName("setAddToCartRequest")
        set(value) {
        _builder.addToCartRequest = value
      }
    /**
     * ```
     * Client → channel
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartRequest add_to_cart_request = 20;`
     */
    public fun clearAddToCartRequest() {
      _builder.clearAddToCartRequest()
    }
    /**
     * ```
     * Client → channel
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartRequest add_to_cart_request = 20;`
     * @return Whether the addToCartRequest field is set.
     */
    public fun hasAddToCartRequest(): kotlin.Boolean {
      return _builder.hasAddToCartRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartResponse add_to_cart_response = 21;`
     */
    public var addToCartResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddToCartResponse
      @kotlin.jvm.JvmName("getAddToCartResponse")
        get() = _builder.addToCartResponse
      @kotlin.jvm.JvmName("setAddToCartResponse")
        set(value) {
        _builder.addToCartResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartResponse add_to_cart_response = 21;`
     */
    public fun clearAddToCartResponse() {
      _builder.clearAddToCartResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartResponse add_to_cart_response = 21;`
     * @return Whether the addToCartResponse field is set.
     */
    public fun hasAddToCartResponse(): kotlin.Boolean {
      return _builder.hasAddToCartResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartRequest remove_from_cart_request = 22;`
     */
    public var removeFromCartRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest
      @kotlin.jvm.JvmName("getRemoveFromCartRequest")
        get() = _builder.removeFromCartRequest
      @kotlin.jvm.JvmName("setRemoveFromCartRequest")
        set(value) {
        _builder.removeFromCartRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartRequest remove_from_cart_request = 22;`
     */
    public fun clearRemoveFromCartRequest() {
      _builder.clearRemoveFromCartRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartRequest remove_from_cart_request = 22;`
     * @return Whether the removeFromCartRequest field is set.
     */
    public fun hasRemoveFromCartRequest(): kotlin.Boolean {
      return _builder.hasRemoveFromCartRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartResponse remove_from_cart_response = 23;`
     */
    public var removeFromCartResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartResponse
      @kotlin.jvm.JvmName("getRemoveFromCartResponse")
        get() = _builder.removeFromCartResponse
      @kotlin.jvm.JvmName("setRemoveFromCartResponse")
        set(value) {
        _builder.removeFromCartResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartResponse remove_from_cart_response = 23;`
     */
    public fun clearRemoveFromCartResponse() {
      _builder.clearRemoveFromCartResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartResponse remove_from_cart_response = 23;`
     * @return Whether the removeFromCartResponse field is set.
     */
    public fun hasRemoveFromCartResponse(): kotlin.Boolean {
      return _builder.hasRemoveFromCartResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartRequest clear_cart_request = 24;`
     */
    public var clearCartRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ClearCartRequest
      @kotlin.jvm.JvmName("getClearCartRequest")
        get() = _builder.clearCartRequest
      @kotlin.jvm.JvmName("setClearCartRequest")
        set(value) {
        _builder.clearCartRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartRequest clear_cart_request = 24;`
     */
    public fun clearClearCartRequest() {
      _builder.clearClearCartRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartRequest clear_cart_request = 24;`
     * @return Whether the clearCartRequest field is set.
     */
    public fun hasClearCartRequest(): kotlin.Boolean {
      return _builder.hasClearCartRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartResponse clear_cart_response = 25;`
     */
    public var clearCartResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ClearCartResponse
      @kotlin.jvm.JvmName("getClearCartResponse")
        get() = _builder.clearCartResponse
      @kotlin.jvm.JvmName("setClearCartResponse")
        set(value) {
        _builder.clearCartResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartResponse clear_cart_response = 25;`
     */
    public fun clearClearCartResponse() {
      _builder.clearClearCartResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartResponse clear_cart_response = 25;`
     * @return Whether the clearCartResponse field is set.
     */
    public fun hasClearCartResponse(): kotlin.Boolean {
      return _builder.hasClearCartResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardRequest guidance_card_request = 26;`
     */
    public var guidanceCardRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest
      @kotlin.jvm.JvmName("getGuidanceCardRequest")
        get() = _builder.guidanceCardRequest
      @kotlin.jvm.JvmName("setGuidanceCardRequest")
        set(value) {
        _builder.guidanceCardRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardRequest guidance_card_request = 26;`
     */
    public fun clearGuidanceCardRequest() {
      _builder.clearGuidanceCardRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardRequest guidance_card_request = 26;`
     * @return Whether the guidanceCardRequest field is set.
     */
    public fun hasGuidanceCardRequest(): kotlin.Boolean {
      return _builder.hasGuidanceCardRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardResponse guidance_card_response = 27;`
     */
    public var guidanceCardResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardResponse
      @kotlin.jvm.JvmName("getGuidanceCardResponse")
        get() = _builder.guidanceCardResponse
      @kotlin.jvm.JvmName("setGuidanceCardResponse")
        set(value) {
        _builder.guidanceCardResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardResponse guidance_card_response = 27;`
     */
    public fun clearGuidanceCardResponse() {
      _builder.clearGuidanceCardResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardResponse guidance_card_response = 27;`
     * @return Whether the guidanceCardResponse field is set.
     */
    public fun hasGuidanceCardResponse(): kotlin.Boolean {
      return _builder.hasGuidanceCardResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionRequest add_promotion_request = 28;`
     */
    public var addPromotionRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddPromotionRequest
      @kotlin.jvm.JvmName("getAddPromotionRequest")
        get() = _builder.addPromotionRequest
      @kotlin.jvm.JvmName("setAddPromotionRequest")
        set(value) {
        _builder.addPromotionRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionRequest add_promotion_request = 28;`
     */
    public fun clearAddPromotionRequest() {
      _builder.clearAddPromotionRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionRequest add_promotion_request = 28;`
     * @return Whether the addPromotionRequest field is set.
     */
    public fun hasAddPromotionRequest(): kotlin.Boolean {
      return _builder.hasAddPromotionRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionResponse add_promotion_response = 29;`
     */
    public var addPromotionResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddPromotionResponse
      @kotlin.jvm.JvmName("getAddPromotionResponse")
        get() = _builder.addPromotionResponse
      @kotlin.jvm.JvmName("setAddPromotionResponse")
        set(value) {
        _builder.addPromotionResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionResponse add_promotion_response = 29;`
     */
    public fun clearAddPromotionResponse() {
      _builder.clearAddPromotionResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionResponse add_promotion_response = 29;`
     * @return Whether the addPromotionResponse field is set.
     */
    public fun hasAddPromotionResponse(): kotlin.Boolean {
      return _builder.hasAddPromotionResponse()
    }

    /**
     * ```
     * Channel → client
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageRequest promotion_message_request = 30;`
     */
    public var promotionMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest
      @kotlin.jvm.JvmName("getPromotionMessageRequest")
        get() = _builder.promotionMessageRequest
      @kotlin.jvm.JvmName("setPromotionMessageRequest")
        set(value) {
        _builder.promotionMessageRequest = value
      }
    /**
     * ```
     * Channel → client
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageRequest promotion_message_request = 30;`
     */
    public fun clearPromotionMessageRequest() {
      _builder.clearPromotionMessageRequest()
    }
    /**
     * ```
     * Channel → client
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageRequest promotion_message_request = 30;`
     * @return Whether the promotionMessageRequest field is set.
     */
    public fun hasPromotionMessageRequest(): kotlin.Boolean {
      return _builder.hasPromotionMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageResponse promotion_message_response = 31;`
     */
    public var promotionMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageResponse
      @kotlin.jvm.JvmName("getPromotionMessageResponse")
        get() = _builder.promotionMessageResponse
      @kotlin.jvm.JvmName("setPromotionMessageResponse")
        set(value) {
        _builder.promotionMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageResponse promotion_message_response = 31;`
     */
    public fun clearPromotionMessageResponse() {
      _builder.clearPromotionMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageResponse promotion_message_response = 31;`
     * @return Whether the promotionMessageResponse field is set.
     */
    public fun hasPromotionMessageResponse(): kotlin.Boolean {
      return _builder.hasPromotionMessageResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageRequest product_message_request = 32;`
     */
    public var productMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest
      @kotlin.jvm.JvmName("getProductMessageRequest")
        get() = _builder.productMessageRequest
      @kotlin.jvm.JvmName("setProductMessageRequest")
        set(value) {
        _builder.productMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageRequest product_message_request = 32;`
     */
    public fun clearProductMessageRequest() {
      _builder.clearProductMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageRequest product_message_request = 32;`
     * @return Whether the productMessageRequest field is set.
     */
    public fun hasProductMessageRequest(): kotlin.Boolean {
      return _builder.hasProductMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageResponse product_message_response = 33;`
     */
    public var productMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageResponse
      @kotlin.jvm.JvmName("getProductMessageResponse")
        get() = _builder.productMessageResponse
      @kotlin.jvm.JvmName("setProductMessageResponse")
        set(value) {
        _builder.productMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageResponse product_message_response = 33;`
     */
    public fun clearProductMessageResponse() {
      _builder.clearProductMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageResponse product_message_response = 33;`
     * @return Whether the productMessageResponse field is set.
     */
    public fun hasProductMessageResponse(): kotlin.Boolean {
      return _builder.hasProductMessageResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusRequest chat_status_request = 34;`
     */
    public var chatStatusRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ChatStatusRequest
      @kotlin.jvm.JvmName("getChatStatusRequest")
        get() = _builder.chatStatusRequest
      @kotlin.jvm.JvmName("setChatStatusRequest")
        set(value) {
        _builder.chatStatusRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusRequest chat_status_request = 34;`
     */
    public fun clearChatStatusRequest() {
      _builder.clearChatStatusRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusRequest chat_status_request = 34;`
     * @return Whether the chatStatusRequest field is set.
     */
    public fun hasChatStatusRequest(): kotlin.Boolean {
      return _builder.hasChatStatusRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusResponse chat_status_response = 35;`
     */
    public var chatStatusResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ChatStatusResponse
      @kotlin.jvm.JvmName("getChatStatusResponse")
        get() = _builder.chatStatusResponse
      @kotlin.jvm.JvmName("setChatStatusResponse")
        set(value) {
        _builder.chatStatusResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusResponse chat_status_response = 35;`
     */
    public fun clearChatStatusResponse() {
      _builder.clearChatStatusResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusResponse chat_status_response = 35;`
     * @return Whether the chatStatusResponse field is set.
     */
    public fun hasChatStatusResponse(): kotlin.Boolean {
      return _builder.hasChatStatusResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomCommandRequest custom_command_request = 36;`
     */
    public var customCommandRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CustomCommandRequest
      @kotlin.jvm.JvmName("getCustomCommandRequest")
        get() = _builder.customCommandRequest
      @kotlin.jvm.JvmName("setCustomCommandRequest")
        set(value) {
        _builder.customCommandRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomCommandRequest custom_command_request = 36;`
     */
    public fun clearCustomCommandRequest() {
      _builder.clearCustomCommandRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomCommandRequest custom_command_request = 36;`
     * @return Whether the customCommandRequest field is set.
     */
    public fun hasCustomCommandRequest(): kotlin.Boolean {
      return _builder.hasCustomCommandRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomCommandResponse custom_command_response = 37;`
     */
    public var customCommandResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CustomCommandResponse
      @kotlin.jvm.JvmName("getCustomCommandResponse")
        get() = _builder.customCommandResponse
      @kotlin.jvm.JvmName("setCustomCommandResponse")
        set(value) {
        _builder.customCommandResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomCommandResponse custom_command_response = 37;`
     */
    public fun clearCustomCommandResponse() {
      _builder.clearCustomCommandResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomCommandResponse custom_command_response = 37;`
     * @return Whether the customCommandResponse field is set.
     */
    public fun hasCustomCommandResponse(): kotlin.Boolean {
      return _builder.hasCustomCommandResponse()
    }

    /**
     * ```
     * Client → channel
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.GetCommandsRequest get_commands_request = 44;`
     */
    public var getCommandsRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsRequest
      @kotlin.jvm.JvmName("getGetCommandsRequest")
        get() = _builder.getCommandsRequest
      @kotlin.jvm.JvmName("setGetCommandsRequest")
        set(value) {
        _builder.getCommandsRequest = value
      }
    /**
     * ```
     * Client → channel
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.GetCommandsRequest get_commands_request = 44;`
     */
    public fun clearGetCommandsRequest() {
      _builder.clearGetCommandsRequest()
    }
    /**
     * ```
     * Client → channel
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.GetCommandsRequest get_commands_request = 44;`
     * @return Whether the getCommandsRequest field is set.
     */
    public fun hasGetCommandsRequest(): kotlin.Boolean {
      return _builder.hasGetCommandsRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.GetCommandsResponse get_commands_response = 45;`
     */
    public var getCommandsResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsResponse
      @kotlin.jvm.JvmName("getGetCommandsResponse")
        get() = _builder.getCommandsResponse
      @kotlin.jvm.JvmName("setGetCommandsResponse")
        set(value) {
        _builder.getCommandsResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GetCommandsResponse get_commands_response = 45;`
     */
    public fun clearGetCommandsResponse() {
      _builder.clearGetCommandsResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GetCommandsResponse get_commands_response = 45;`
     * @return Whether the getCommandsResponse field is set.
     */
    public fun hasGetCommandsResponse(): kotlin.Boolean {
      return _builder.hasGetCommandsResponse()
    }
    public val payloadCase: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.PayloadCase
    @kotlin.jvm.JvmName("getPayloadCase")
      get() = _builder.payloadCase

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.copy(block: `yalo.external_channel.in_app.sdk.v1`.SdkMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage =
  `yalo.external_channel.in_app.sdk.v1`.SdkMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.textMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.TextMessageRequest?
  get() = if (hasTextMessageRequest()) getTextMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.voiceNoteMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceNoteMessageRequest?
  get() = if (hasVoiceNoteMessageRequest()) getVoiceNoteMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.imageMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessageRequest?
  get() = if (hasImageMessageRequest()) getImageMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.messageReceiptRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest?
  get() = if (hasMessageReceiptRequest()) getMessageReceiptRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.attachmentMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AttachmentMessageRequest?
  get() = if (hasAttachmentMessageRequest()) getAttachmentMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.videoMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest?
  get() = if (hasVideoMessageRequest()) getVideoMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.addToCartRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddToCartRequest?
  get() = if (hasAddToCartRequest()) getAddToCartRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.addToCartResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddToCartResponse?
  get() = if (hasAddToCartResponse()) getAddToCartResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.removeFromCartRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest?
  get() = if (hasRemoveFromCartRequest()) getRemoveFromCartRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.removeFromCartResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartResponse?
  get() = if (hasRemoveFromCartResponse()) getRemoveFromCartResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.clearCartRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ClearCartRequest?
  get() = if (hasClearCartRequest()) getClearCartRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.clearCartResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ClearCartResponse?
  get() = if (hasClearCartResponse()) getClearCartResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.guidanceCardRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest?
  get() = if (hasGuidanceCardRequest()) getGuidanceCardRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.guidanceCardResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardResponse?
  get() = if (hasGuidanceCardResponse()) getGuidanceCardResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.addPromotionRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddPromotionRequest?
  get() = if (hasAddPromotionRequest()) getAddPromotionRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.addPromotionResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddPromotionResponse?
  get() = if (hasAddPromotionResponse()) getAddPromotionResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.promotionMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest?
  get() = if (hasPromotionMessageRequest()) getPromotionMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.promotionMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageResponse?
  get() = if (hasPromotionMessageResponse()) getPromotionMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.productMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest?
  get() = if (hasProductMessageRequest()) getProductMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.productMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageResponse?
  get() = if (hasProductMessageResponse()) getProductMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.chatStatusRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ChatStatusRequest?
  get() = if (hasChatStatusRequest()) getChatStatusRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.chatStatusResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ChatStatusResponse?
  get() = if (hasChatStatusResponse()) getChatStatusResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.customCommandRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CustomCommandRequest?
  get() = if (hasCustomCommandRequest()) getCustomCommandRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.customCommandResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CustomCommandResponse?
  get() = if (hasCustomCommandResponse()) getCustomCommandResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.getCommandsRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsRequest?
  get() = if (hasGetCommandsRequest()) getGetCommandsRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.getCommandsResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GetCommandsResponse?
  get() = if (hasGetCommandsResponse()) getGetCommandsResponse() else null

