// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializesdkMessage")
public inline fun sdkMessage(block: yalo.external_channel.in_app.sdk.v1.SdkMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage =
  yalo.external_channel.in_app.sdk.v1.SdkMessageKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * SdkMessage is the top-level wrapper sent over the bidirectional stream.
 * Exactly one payload field is set per message; the oneof lets the Go runtime
 * expose a type-switch-friendly isSdkMessage_Payload interface.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.SdkMessage`
 */
public object SdkMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage = _builder.build()

    /**
     * ```
     * A client-generated id that can be used to correlate requests with responses.
     * ```
     *
     * `string correlation_id = 1;`
     */
    public var correlationId: kotlin.String
      @kotlin.jvm.JvmName("getCorrelationId")
        get() = _builder.correlationId
      @kotlin.jvm.JvmName("setCorrelationId")
        set(value) {
        _builder.correlationId = value
      }
    /**
     * ```
     * A client-generated id that can be used to correlate requests with responses.
     * ```
     *
     * `string correlation_id = 1;`
     */
    public fun clearCorrelationId() {
      _builder.clearCorrelationId()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val SdkMessageKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * ```
     * Bi-directional
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.TextMessageRequest text_message_request = 10;`
     */
    public var textMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.TextMessageRequest
      @kotlin.jvm.JvmName("getTextMessageRequest")
        get() = _builder.textMessageRequest
      @kotlin.jvm.JvmName("setTextMessageRequest")
        set(value) {
        _builder.textMessageRequest = value
      }
    /**
     * ```
     * Bi-directional
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.TextMessageRequest text_message_request = 10;`
     */
    public fun clearTextMessageRequest() {
      _builder.clearTextMessageRequest()
    }
    /**
     * ```
     * Bi-directional
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.TextMessageRequest text_message_request = 10;`
     * @return Whether the textMessageRequest field is set.
     */
    public fun hasTextMessageRequest(): kotlin.Boolean {
      return _builder.hasTextMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.TextMessageResponse text_message_response = 11;`
     */
    public var textMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.TextMessageResponse
      @kotlin.jvm.JvmName("getTextMessageResponse")
        get() = _builder.textMessageResponse
      @kotlin.jvm.JvmName("setTextMessageResponse")
        set(value) {
        _builder.textMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.TextMessageResponse text_message_response = 11;`
     */
    public fun clearTextMessageResponse() {
      _builder.clearTextMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.TextMessageResponse text_message_response = 11;`
     * @return Whether the textMessageResponse field is set.
     */
    public fun hasTextMessageResponse(): kotlin.Boolean {
      return _builder.hasTextMessageResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.VoiceNoteMessageRequest voice_note_message_request = 12;`
     */
    public var voiceNoteMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceNoteMessageRequest
      @kotlin.jvm.JvmName("getVoiceNoteMessageRequest")
        get() = _builder.voiceNoteMessageRequest
      @kotlin.jvm.JvmName("setVoiceNoteMessageRequest")
        set(value) {
        _builder.voiceNoteMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VoiceNoteMessageRequest voice_note_message_request = 12;`
     */
    public fun clearVoiceNoteMessageRequest() {
      _builder.clearVoiceNoteMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VoiceNoteMessageRequest voice_note_message_request = 12;`
     * @return Whether the voiceNoteMessageRequest field is set.
     */
    public fun hasVoiceNoteMessageRequest(): kotlin.Boolean {
      return _builder.hasVoiceNoteMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.VoiceNoteMessageResponse voice_note_message_response = 13;`
     */
    public var voiceNoteMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceNoteMessageResponse
      @kotlin.jvm.JvmName("getVoiceNoteMessageResponse")
        get() = _builder.voiceNoteMessageResponse
      @kotlin.jvm.JvmName("setVoiceNoteMessageResponse")
        set(value) {
        _builder.voiceNoteMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VoiceNoteMessageResponse voice_note_message_response = 13;`
     */
    public fun clearVoiceNoteMessageResponse() {
      _builder.clearVoiceNoteMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VoiceNoteMessageResponse voice_note_message_response = 13;`
     * @return Whether the voiceNoteMessageResponse field is set.
     */
    public fun hasVoiceNoteMessageResponse(): kotlin.Boolean {
      return _builder.hasVoiceNoteMessageResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ImageMessageRequest image_message_request = 14;`
     */
    public var imageMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessageRequest
      @kotlin.jvm.JvmName("getImageMessageRequest")
        get() = _builder.imageMessageRequest
      @kotlin.jvm.JvmName("setImageMessageRequest")
        set(value) {
        _builder.imageMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ImageMessageRequest image_message_request = 14;`
     */
    public fun clearImageMessageRequest() {
      _builder.clearImageMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ImageMessageRequest image_message_request = 14;`
     * @return Whether the imageMessageRequest field is set.
     */
    public fun hasImageMessageRequest(): kotlin.Boolean {
      return _builder.hasImageMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ImageMessageResponse image_message_response = 15;`
     */
    public var imageMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessageResponse
      @kotlin.jvm.JvmName("getImageMessageResponse")
        get() = _builder.imageMessageResponse
      @kotlin.jvm.JvmName("setImageMessageResponse")
        set(value) {
        _builder.imageMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ImageMessageResponse image_message_response = 15;`
     */
    public fun clearImageMessageResponse() {
      _builder.clearImageMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ImageMessageResponse image_message_response = 15;`
     * @return Whether the imageMessageResponse field is set.
     */
    public fun hasImageMessageResponse(): kotlin.Boolean {
      return _builder.hasImageMessageResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageReceiptRequest message_receipt_request = 16;`
     */
    public var messageReceiptRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest
      @kotlin.jvm.JvmName("getMessageReceiptRequest")
        get() = _builder.messageReceiptRequest
      @kotlin.jvm.JvmName("setMessageReceiptRequest")
        set(value) {
        _builder.messageReceiptRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageReceiptRequest message_receipt_request = 16;`
     */
    public fun clearMessageReceiptRequest() {
      _builder.clearMessageReceiptRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageReceiptRequest message_receipt_request = 16;`
     * @return Whether the messageReceiptRequest field is set.
     */
    public fun hasMessageReceiptRequest(): kotlin.Boolean {
      return _builder.hasMessageReceiptRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageReceiptResponse message_receipt_response = 17;`
     */
    public var messageReceiptResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptResponse
      @kotlin.jvm.JvmName("getMessageReceiptResponse")
        get() = _builder.messageReceiptResponse
      @kotlin.jvm.JvmName("setMessageReceiptResponse")
        set(value) {
        _builder.messageReceiptResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageReceiptResponse message_receipt_response = 17;`
     */
    public fun clearMessageReceiptResponse() {
      _builder.clearMessageReceiptResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageReceiptResponse message_receipt_response = 17;`
     * @return Whether the messageReceiptResponse field is set.
     */
    public fun hasMessageReceiptResponse(): kotlin.Boolean {
      return _builder.hasMessageReceiptResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.AttachmentMessageRequest attachment_message_request = 18;`
     */
    public var attachmentMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AttachmentMessageRequest
      @kotlin.jvm.JvmName("getAttachmentMessageRequest")
        get() = _builder.attachmentMessageRequest
      @kotlin.jvm.JvmName("setAttachmentMessageRequest")
        set(value) {
        _builder.attachmentMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AttachmentMessageRequest attachment_message_request = 18;`
     */
    public fun clearAttachmentMessageRequest() {
      _builder.clearAttachmentMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AttachmentMessageRequest attachment_message_request = 18;`
     * @return Whether the attachmentMessageRequest field is set.
     */
    public fun hasAttachmentMessageRequest(): kotlin.Boolean {
      return _builder.hasAttachmentMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.AttachmentMessageResponse attachment_message_response = 19;`
     */
    public var attachmentMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AttachmentMessageResponse
      @kotlin.jvm.JvmName("getAttachmentMessageResponse")
        get() = _builder.attachmentMessageResponse
      @kotlin.jvm.JvmName("setAttachmentMessageResponse")
        set(value) {
        _builder.attachmentMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AttachmentMessageResponse attachment_message_response = 19;`
     */
    public fun clearAttachmentMessageResponse() {
      _builder.clearAttachmentMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AttachmentMessageResponse attachment_message_response = 19;`
     * @return Whether the attachmentMessageResponse field is set.
     */
    public fun hasAttachmentMessageResponse(): kotlin.Boolean {
      return _builder.hasAttachmentMessageResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessageRequest video_message_request = 38;`
     */
    public var videoMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest
      @kotlin.jvm.JvmName("getVideoMessageRequest")
        get() = _builder.videoMessageRequest
      @kotlin.jvm.JvmName("setVideoMessageRequest")
        set(value) {
        _builder.videoMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessageRequest video_message_request = 38;`
     */
    public fun clearVideoMessageRequest() {
      _builder.clearVideoMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessageRequest video_message_request = 38;`
     * @return Whether the videoMessageRequest field is set.
     */
    public fun hasVideoMessageRequest(): kotlin.Boolean {
      return _builder.hasVideoMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessageResponse video_message_response = 39;`
     */
    public var videoMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageResponse
      @kotlin.jvm.JvmName("getVideoMessageResponse")
        get() = _builder.videoMessageResponse
      @kotlin.jvm.JvmName("setVideoMessageResponse")
        set(value) {
        _builder.videoMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessageResponse video_message_response = 39;`
     */
    public fun clearVideoMessageResponse() {
      _builder.clearVideoMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessageResponse video_message_response = 39;`
     * @return Whether the videoMessageResponse field is set.
     */
    public fun hasVideoMessageResponse(): kotlin.Boolean {
      return _builder.hasVideoMessageResponse()
    }

    /**
     * ```
     * Client → channel
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartRequest add_to_cart_request = 20;`
     */
    public var addToCartRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddToCartRequest
      @kotlin.jvm.JvmName("getAddToCartRequest")
        get() = _builder.addToCartRequest
      @kotlin.jvm.JvmName("setAddToCartRequest")
        set(value) {
        _builder.addToCartRequest = value
      }
    /**
     * ```
     * Client → channel
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartRequest add_to_cart_request = 20;`
     */
    public fun clearAddToCartRequest() {
      _builder.clearAddToCartRequest()
    }
    /**
     * ```
     * Client → channel
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartRequest add_to_cart_request = 20;`
     * @return Whether the addToCartRequest field is set.
     */
    public fun hasAddToCartRequest(): kotlin.Boolean {
      return _builder.hasAddToCartRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartResponse add_to_cart_response = 21;`
     */
    public var addToCartResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddToCartResponse
      @kotlin.jvm.JvmName("getAddToCartResponse")
        get() = _builder.addToCartResponse
      @kotlin.jvm.JvmName("setAddToCartResponse")
        set(value) {
        _builder.addToCartResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartResponse add_to_cart_response = 21;`
     */
    public fun clearAddToCartResponse() {
      _builder.clearAddToCartResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddToCartResponse add_to_cart_response = 21;`
     * @return Whether the addToCartResponse field is set.
     */
    public fun hasAddToCartResponse(): kotlin.Boolean {
      return _builder.hasAddToCartResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartRequest remove_from_cart_request = 22;`
     */
    public var removeFromCartRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest
      @kotlin.jvm.JvmName("getRemoveFromCartRequest")
        get() = _builder.removeFromCartRequest
      @kotlin.jvm.JvmName("setRemoveFromCartRequest")
        set(value) {
        _builder.removeFromCartRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartRequest remove_from_cart_request = 22;`
     */
    public fun clearRemoveFromCartRequest() {
      _builder.clearRemoveFromCartRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartRequest remove_from_cart_request = 22;`
     * @return Whether the removeFromCartRequest field is set.
     */
    public fun hasRemoveFromCartRequest(): kotlin.Boolean {
      return _builder.hasRemoveFromCartRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartResponse remove_from_cart_response = 23;`
     */
    public var removeFromCartResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartResponse
      @kotlin.jvm.JvmName("getRemoveFromCartResponse")
        get() = _builder.removeFromCartResponse
      @kotlin.jvm.JvmName("setRemoveFromCartResponse")
        set(value) {
        _builder.removeFromCartResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartResponse remove_from_cart_response = 23;`
     */
    public fun clearRemoveFromCartResponse() {
      _builder.clearRemoveFromCartResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.RemoveFromCartResponse remove_from_cart_response = 23;`
     * @return Whether the removeFromCartResponse field is set.
     */
    public fun hasRemoveFromCartResponse(): kotlin.Boolean {
      return _builder.hasRemoveFromCartResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartRequest clear_cart_request = 24;`
     */
    public var clearCartRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ClearCartRequest
      @kotlin.jvm.JvmName("getClearCartRequest")
        get() = _builder.clearCartRequest
      @kotlin.jvm.JvmName("setClearCartRequest")
        set(value) {
        _builder.clearCartRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartRequest clear_cart_request = 24;`
     */
    public fun clearClearCartRequest() {
      _builder.clearClearCartRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartRequest clear_cart_request = 24;`
     * @return Whether the clearCartRequest field is set.
     */
    public fun hasClearCartRequest(): kotlin.Boolean {
      return _builder.hasClearCartRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartResponse clear_cart_response = 25;`
     */
    public var clearCartResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ClearCartResponse
      @kotlin.jvm.JvmName("getClearCartResponse")
        get() = _builder.clearCartResponse
      @kotlin.jvm.JvmName("setClearCartResponse")
        set(value) {
        _builder.clearCartResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartResponse clear_cart_response = 25;`
     */
    public fun clearClearCartResponse() {
      _builder.clearClearCartResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ClearCartResponse clear_cart_response = 25;`
     * @return Whether the clearCartResponse field is set.
     */
    public fun hasClearCartResponse(): kotlin.Boolean {
      return _builder.hasClearCartResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardRequest guidance_card_request = 26;`
     */
    public var guidanceCardRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest
      @kotlin.jvm.JvmName("getGuidanceCardRequest")
        get() = _builder.guidanceCardRequest
      @kotlin.jvm.JvmName("setGuidanceCardRequest")
        set(value) {
        _builder.guidanceCardRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardRequest guidance_card_request = 26;`
     */
    public fun clearGuidanceCardRequest() {
      _builder.clearGuidanceCardRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardRequest guidance_card_request = 26;`
     * @return Whether the guidanceCardRequest field is set.
     */
    public fun hasGuidanceCardRequest(): kotlin.Boolean {
      return _builder.hasGuidanceCardRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardResponse guidance_card_response = 27;`
     */
    public var guidanceCardResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardResponse
      @kotlin.jvm.JvmName("getGuidanceCardResponse")
        get() = _builder.guidanceCardResponse
      @kotlin.jvm.JvmName("setGuidanceCardResponse")
        set(value) {
        _builder.guidanceCardResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardResponse guidance_card_response = 27;`
     */
    public fun clearGuidanceCardResponse() {
      _builder.clearGuidanceCardResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.GuidanceCardResponse guidance_card_response = 27;`
     * @return Whether the guidanceCardResponse field is set.
     */
    public fun hasGuidanceCardResponse(): kotlin.Boolean {
      return _builder.hasGuidanceCardResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionRequest add_promotion_request = 28;`
     */
    public var addPromotionRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddPromotionRequest
      @kotlin.jvm.JvmName("getAddPromotionRequest")
        get() = _builder.addPromotionRequest
      @kotlin.jvm.JvmName("setAddPromotionRequest")
        set(value) {
        _builder.addPromotionRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionRequest add_promotion_request = 28;`
     */
    public fun clearAddPromotionRequest() {
      _builder.clearAddPromotionRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionRequest add_promotion_request = 28;`
     * @return Whether the addPromotionRequest field is set.
     */
    public fun hasAddPromotionRequest(): kotlin.Boolean {
      return _builder.hasAddPromotionRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionResponse add_promotion_response = 29;`
     */
    public var addPromotionResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddPromotionResponse
      @kotlin.jvm.JvmName("getAddPromotionResponse")
        get() = _builder.addPromotionResponse
      @kotlin.jvm.JvmName("setAddPromotionResponse")
        set(value) {
        _builder.addPromotionResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionResponse add_promotion_response = 29;`
     */
    public fun clearAddPromotionResponse() {
      _builder.clearAddPromotionResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.AddPromotionResponse add_promotion_response = 29;`
     * @return Whether the addPromotionResponse field is set.
     */
    public fun hasAddPromotionResponse(): kotlin.Boolean {
      return _builder.hasAddPromotionResponse()
    }

    /**
     * ```
     * Channel → client
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageRequest promotion_message_request = 30;`
     */
    public var promotionMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest
      @kotlin.jvm.JvmName("getPromotionMessageRequest")
        get() = _builder.promotionMessageRequest
      @kotlin.jvm.JvmName("setPromotionMessageRequest")
        set(value) {
        _builder.promotionMessageRequest = value
      }
    /**
     * ```
     * Channel → client
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageRequest promotion_message_request = 30;`
     */
    public fun clearPromotionMessageRequest() {
      _builder.clearPromotionMessageRequest()
    }
    /**
     * ```
     * Channel → client
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageRequest promotion_message_request = 30;`
     * @return Whether the promotionMessageRequest field is set.
     */
    public fun hasPromotionMessageRequest(): kotlin.Boolean {
      return _builder.hasPromotionMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageResponse promotion_message_response = 31;`
     */
    public var promotionMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageResponse
      @kotlin.jvm.JvmName("getPromotionMessageResponse")
        get() = _builder.promotionMessageResponse
      @kotlin.jvm.JvmName("setPromotionMessageResponse")
        set(value) {
        _builder.promotionMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageResponse promotion_message_response = 31;`
     */
    public fun clearPromotionMessageResponse() {
      _builder.clearPromotionMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.PromotionMessageResponse promotion_message_response = 31;`
     * @return Whether the promotionMessageResponse field is set.
     */
    public fun hasPromotionMessageResponse(): kotlin.Boolean {
      return _builder.hasPromotionMessageResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageRequest product_message_request = 32;`
     */
    public var productMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest
      @kotlin.jvm.JvmName("getProductMessageRequest")
        get() = _builder.productMessageRequest
      @kotlin.jvm.JvmName("setProductMessageRequest")
        set(value) {
        _builder.productMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageRequest product_message_request = 32;`
     */
    public fun clearProductMessageRequest() {
      _builder.clearProductMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageRequest product_message_request = 32;`
     * @return Whether the productMessageRequest field is set.
     */
    public fun hasProductMessageRequest(): kotlin.Boolean {
      return _builder.hasProductMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageResponse product_message_response = 33;`
     */
    public var productMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageResponse
      @kotlin.jvm.JvmName("getProductMessageResponse")
        get() = _builder.productMessageResponse
      @kotlin.jvm.JvmName("setProductMessageResponse")
        set(value) {
        _builder.productMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageResponse product_message_response = 33;`
     */
    public fun clearProductMessageResponse() {
      _builder.clearProductMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ProductMessageResponse product_message_response = 33;`
     * @return Whether the productMessageResponse field is set.
     */
    public fun hasProductMessageResponse(): kotlin.Boolean {
      return _builder.hasProductMessageResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusRequest chat_status_request = 34;`
     */
    public var chatStatusRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ChatStatusRequest
      @kotlin.jvm.JvmName("getChatStatusRequest")
        get() = _builder.chatStatusRequest
      @kotlin.jvm.JvmName("setChatStatusRequest")
        set(value) {
        _builder.chatStatusRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusRequest chat_status_request = 34;`
     */
    public fun clearChatStatusRequest() {
      _builder.clearChatStatusRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusRequest chat_status_request = 34;`
     * @return Whether the chatStatusRequest field is set.
     */
    public fun hasChatStatusRequest(): kotlin.Boolean {
      return _builder.hasChatStatusRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusResponse chat_status_response = 35;`
     */
    public var chatStatusResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ChatStatusResponse
      @kotlin.jvm.JvmName("getChatStatusResponse")
        get() = _builder.chatStatusResponse
      @kotlin.jvm.JvmName("setChatStatusResponse")
        set(value) {
        _builder.chatStatusResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusResponse chat_status_response = 35;`
     */
    public fun clearChatStatusResponse() {
      _builder.clearChatStatusResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ChatStatusResponse chat_status_response = 35;`
     * @return Whether the chatStatusResponse field is set.
     */
    public fun hasChatStatusResponse(): kotlin.Boolean {
      return _builder.hasChatStatusResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomActionRequest custom_action_request = 36;`
     */
    public var customActionRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CustomActionRequest
      @kotlin.jvm.JvmName("getCustomActionRequest")
        get() = _builder.customActionRequest
      @kotlin.jvm.JvmName("setCustomActionRequest")
        set(value) {
        _builder.customActionRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomActionRequest custom_action_request = 36;`
     */
    public fun clearCustomActionRequest() {
      _builder.clearCustomActionRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomActionRequest custom_action_request = 36;`
     * @return Whether the customActionRequest field is set.
     */
    public fun hasCustomActionRequest(): kotlin.Boolean {
      return _builder.hasCustomActionRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomActionResponse custom_action_response = 37;`
     */
    public var customActionResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CustomActionResponse
      @kotlin.jvm.JvmName("getCustomActionResponse")
        get() = _builder.customActionResponse
      @kotlin.jvm.JvmName("setCustomActionResponse")
        set(value) {
        _builder.customActionResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomActionResponse custom_action_response = 37;`
     */
    public fun clearCustomActionResponse() {
      _builder.clearCustomActionResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CustomActionResponse custom_action_response = 37;`
     * @return Whether the customActionResponse field is set.
     */
    public fun hasCustomActionResponse(): kotlin.Boolean {
      return _builder.hasCustomActionResponse()
    }

    /**
     * ```
     * Channel → client
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.ButtonsMessageRequest buttons_message_request = 40;`
     */
    public var buttonsMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ButtonsMessageRequest
      @kotlin.jvm.JvmName("getButtonsMessageRequest")
        get() = _builder.buttonsMessageRequest
      @kotlin.jvm.JvmName("setButtonsMessageRequest")
        set(value) {
        _builder.buttonsMessageRequest = value
      }
    /**
     * ```
     * Channel → client
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.ButtonsMessageRequest buttons_message_request = 40;`
     */
    public fun clearButtonsMessageRequest() {
      _builder.clearButtonsMessageRequest()
    }
    /**
     * ```
     * Channel → client
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v1.ButtonsMessageRequest buttons_message_request = 40;`
     * @return Whether the buttonsMessageRequest field is set.
     */
    public fun hasButtonsMessageRequest(): kotlin.Boolean {
      return _builder.hasButtonsMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ButtonsMessageResponse buttons_message_response = 41;`
     */
    public var buttonsMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ButtonsMessageResponse
      @kotlin.jvm.JvmName("getButtonsMessageResponse")
        get() = _builder.buttonsMessageResponse
      @kotlin.jvm.JvmName("setButtonsMessageResponse")
        set(value) {
        _builder.buttonsMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ButtonsMessageResponse buttons_message_response = 41;`
     */
    public fun clearButtonsMessageResponse() {
      _builder.clearButtonsMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ButtonsMessageResponse buttons_message_response = 41;`
     * @return Whether the buttonsMessageResponse field is set.
     */
    public fun hasButtonsMessageResponse(): kotlin.Boolean {
      return _builder.hasButtonsMessageResponse()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.CTAMessageRequest cta_message_request = 42;`
     */
    public var ctaMessageRequest: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequest
      @kotlin.jvm.JvmName("getCtaMessageRequest")
        get() = _builder.ctaMessageRequest
      @kotlin.jvm.JvmName("setCtaMessageRequest")
        set(value) {
        _builder.ctaMessageRequest = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CTAMessageRequest cta_message_request = 42;`
     */
    public fun clearCtaMessageRequest() {
      _builder.clearCtaMessageRequest()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CTAMessageRequest cta_message_request = 42;`
     * @return Whether the ctaMessageRequest field is set.
     */
    public fun hasCtaMessageRequest(): kotlin.Boolean {
      return _builder.hasCtaMessageRequest()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.CTAMessageResponse cta_message_response = 43;`
     */
    public var ctaMessageResponse: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageResponse
      @kotlin.jvm.JvmName("getCtaMessageResponse")
        get() = _builder.ctaMessageResponse
      @kotlin.jvm.JvmName("setCtaMessageResponse")
        set(value) {
        _builder.ctaMessageResponse = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CTAMessageResponse cta_message_response = 43;`
     */
    public fun clearCtaMessageResponse() {
      _builder.clearCtaMessageResponse()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.CTAMessageResponse cta_message_response = 43;`
     * @return Whether the ctaMessageResponse field is set.
     */
    public fun hasCtaMessageResponse(): kotlin.Boolean {
      return _builder.hasCtaMessageResponse()
    }
    public val payloadCase: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.PayloadCase
    @kotlin.jvm.JvmName("getPayloadCase")
      get() = _builder.payloadCase

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage.copy(block: `yalo.external_channel.in_app.sdk.v1`.SdkMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessage =
  `yalo.external_channel.in_app.sdk.v1`.SdkMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.textMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.TextMessageRequest?
  get() = if (hasTextMessageRequest()) getTextMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.textMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.TextMessageResponse?
  get() = if (hasTextMessageResponse()) getTextMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.voiceNoteMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceNoteMessageRequest?
  get() = if (hasVoiceNoteMessageRequest()) getVoiceNoteMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.voiceNoteMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceNoteMessageResponse?
  get() = if (hasVoiceNoteMessageResponse()) getVoiceNoteMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.imageMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessageRequest?
  get() = if (hasImageMessageRequest()) getImageMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.imageMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ImageMessageResponse?
  get() = if (hasImageMessageResponse()) getImageMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.messageReceiptRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptRequest?
  get() = if (hasMessageReceiptRequest()) getMessageReceiptRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.messageReceiptResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageReceiptResponse?
  get() = if (hasMessageReceiptResponse()) getMessageReceiptResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.attachmentMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AttachmentMessageRequest?
  get() = if (hasAttachmentMessageRequest()) getAttachmentMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.attachmentMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AttachmentMessageResponse?
  get() = if (hasAttachmentMessageResponse()) getAttachmentMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.videoMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest?
  get() = if (hasVideoMessageRequest()) getVideoMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.videoMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageResponse?
  get() = if (hasVideoMessageResponse()) getVideoMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.addToCartRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddToCartRequest?
  get() = if (hasAddToCartRequest()) getAddToCartRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.addToCartResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddToCartResponse?
  get() = if (hasAddToCartResponse()) getAddToCartResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.removeFromCartRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartRequest?
  get() = if (hasRemoveFromCartRequest()) getRemoveFromCartRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.removeFromCartResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.RemoveFromCartResponse?
  get() = if (hasRemoveFromCartResponse()) getRemoveFromCartResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.clearCartRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ClearCartRequest?
  get() = if (hasClearCartRequest()) getClearCartRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.clearCartResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ClearCartResponse?
  get() = if (hasClearCartResponse()) getClearCartResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.guidanceCardRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardRequest?
  get() = if (hasGuidanceCardRequest()) getGuidanceCardRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.guidanceCardResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.GuidanceCardResponse?
  get() = if (hasGuidanceCardResponse()) getGuidanceCardResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.addPromotionRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddPromotionRequest?
  get() = if (hasAddPromotionRequest()) getAddPromotionRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.addPromotionResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.AddPromotionResponse?
  get() = if (hasAddPromotionResponse()) getAddPromotionResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.promotionMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageRequest?
  get() = if (hasPromotionMessageRequest()) getPromotionMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.promotionMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.PromotionMessageResponse?
  get() = if (hasPromotionMessageResponse()) getPromotionMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.productMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageRequest?
  get() = if (hasProductMessageRequest()) getProductMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.productMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ProductMessageResponse?
  get() = if (hasProductMessageResponse()) getProductMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.chatStatusRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ChatStatusRequest?
  get() = if (hasChatStatusRequest()) getChatStatusRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.chatStatusResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ChatStatusResponse?
  get() = if (hasChatStatusResponse()) getChatStatusResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.customActionRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CustomActionRequest?
  get() = if (hasCustomActionRequest()) getCustomActionRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.customActionResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CustomActionResponse?
  get() = if (hasCustomActionResponse()) getCustomActionResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.buttonsMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ButtonsMessageRequest?
  get() = if (hasButtonsMessageRequest()) getButtonsMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.buttonsMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ButtonsMessageResponse?
  get() = if (hasButtonsMessageResponse()) getButtonsMessageResponse() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.ctaMessageRequestOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageRequest?
  get() = if (hasCtaMessageRequest()) getCtaMessageRequest() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.SdkMessageOrBuilder.ctaMessageResponseOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.CTAMessageResponse?
  get() = if (hasCtaMessageResponse()) getCtaMessageResponse() else null

