// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializevideoMessageRequest")
public inline fun videoMessageRequest(block: yalo.external_channel.in_app.sdk.v1.VideoMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest =
  yalo.external_channel.in_app.sdk.v1.VideoMessageRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * VideoMessageRequest is sent by either party to deliver a video.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.VideoMessageRequest`
 */
public object VideoMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest = _builder.build()

    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessage content = 1;`
     */
    public var content: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessage
      @kotlin.jvm.JvmName("getContent")
        get() = _builder.content
      @kotlin.jvm.JvmName("setContent")
        set(value) {
        _builder.content = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessage content = 1;`
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.VideoMessage content = 1;`
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }

    public val VideoMessageRequestKt.Dsl.contentOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessage?
      get() = _builder.contentOrNull

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val VideoMessageRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class QuickRepliesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string quick_replies = 3;`
     * @return A list containing the quickReplies.
     */
    public val quickReplies: com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.quickRepliesList
      )
    /**
     * `repeated string quick_replies = 3;`
     * @param value The quickReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addQuickReplies")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.add(value: kotlin.String) {
      _builder.addQuickReplies(value)
    }
    /**
     * `repeated string quick_replies = 3;`
     * @param value The quickReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignQuickReplies")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string quick_replies = 3;`
     * @param values The quickReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllQuickReplies")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllQuickReplies(values)
    }
    /**
     * `repeated string quick_replies = 3;`
     * @param values The quickReplies to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllQuickReplies")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string quick_replies = 3;`
     * @param index The index to set the value at.
     * @param value The quickReplies to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setQuickReplies")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setQuickReplies(index, value)
    }/**
     * `repeated string quick_replies = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setQuickReplies")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, QuickRepliesProxy>.clear() {
      _builder.clearQuickReplies()
    }}
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest.copy(block: `yalo.external_channel.in_app.sdk.v1`.VideoMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequest =
  `yalo.external_channel.in_app.sdk.v1`.VideoMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequestOrBuilder.contentOrNull: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessage?
  get() = if (hasContent()) getContent() else null

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VideoMessageRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

