// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializevoiceMessageResponse")
public inline fun voiceMessageResponse(block: yalo.external_channel.in_app.sdk.v1.VoiceMessageResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessageResponse =
  yalo.external_channel.in_app.sdk.v1.VoiceMessageResponseKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessageResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * VoiceMessageResponse acknowledges a VoiceMessageRequest and returns the assigned message id.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.VoiceMessageResponse`
 */
public object VoiceMessageResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessageResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessageResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessageResponse = _builder.build()

    /**
     * `.yalo.external_channel.in_app.sdk.v1.ResponseStatus status = 1;`
     */
    public var status: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.ResponseStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.ResponseStatus status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val VoiceMessageResponseKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * `string message_id = 3;`
     */
    public var messageId: kotlin.String
      @kotlin.jvm.JvmName("getMessageId")
        get() = _builder.messageId
      @kotlin.jvm.JvmName("setMessageId")
        set(value) {
        _builder.messageId = value
      }
    /**
     * `string message_id = 3;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessageResponse.copy(block: `yalo.external_channel.in_app.sdk.v1`.VoiceMessageResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessageResponse =
  `yalo.external_channel.in_app.sdk.v1`.VoiceMessageResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessageResponseOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

