// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v1;

@kotlin.jvm.JvmName("-initializevoiceMessage")
public inline fun voiceMessage(block: yalo.external_channel.in_app.sdk.v1.VoiceMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessage =
  yalo.external_channel.in_app.sdk.v1.VoiceMessageKt.Dsl._create(yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * VoiceMessage holds the payload of a voice-note conversation turn.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v1.VoiceMessage`
 */
public object VoiceMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessage = _builder.build()

    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val VoiceMessageKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * `string media_url = 2;`
     */
    public var mediaUrl: kotlin.String
      @kotlin.jvm.JvmName("getMediaUrl")
        get() = _builder.mediaUrl
      @kotlin.jvm.JvmName("setMediaUrl")
        set(value) {
        _builder.mediaUrl = value
      }
    /**
     * `string media_url = 2;`
     */
    public fun clearMediaUrl() {
      _builder.clearMediaUrl()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AmplitudesPreviewProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Amplitude samples used to render the waveform preview in the UI.
     * ```
     *
     * `repeated float amplitudes_preview = 3;`
     */
     public val amplitudesPreview: com.google.protobuf.kotlin.DslList<kotlin.Float, AmplitudesPreviewProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.amplitudesPreviewList
      )
    /**
     * ```
     * Amplitude samples used to render the waveform preview in the UI.
     * ```
     *
     * `repeated float amplitudes_preview = 3;`
     * @param value The amplitudesPreview to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAmplitudesPreview")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, AmplitudesPreviewProxy>.add(value: kotlin.Float) {
      _builder.addAmplitudesPreview(value)
    }/**
     * ```
     * Amplitude samples used to render the waveform preview in the UI.
     * ```
     *
     * `repeated float amplitudes_preview = 3;`
     * @param value The amplitudesPreview to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAmplitudesPreview")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, AmplitudesPreviewProxy>.plusAssign(value: kotlin.Float) {
      add(value)
    }/**
     * ```
     * Amplitude samples used to render the waveform preview in the UI.
     * ```
     *
     * `repeated float amplitudes_preview = 3;`
     * @param values The amplitudesPreview to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllAmplitudesPreview")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, AmplitudesPreviewProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Float>) {
      _builder.addAllAmplitudesPreview(values)
    }/**
     * ```
     * Amplitude samples used to render the waveform preview in the UI.
     * ```
     *
     * `repeated float amplitudes_preview = 3;`
     * @param values The amplitudesPreview to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllAmplitudesPreview")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, AmplitudesPreviewProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Float>) {
      addAll(values)
    }/**
     * ```
     * Amplitude samples used to render the waveform preview in the UI.
     * ```
     *
     * `repeated float amplitudes_preview = 3;`
     * @param index The index to set the value at.
     * @param value The amplitudesPreview to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAmplitudesPreview")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Float, AmplitudesPreviewProxy>.set(index: kotlin.Int, value: kotlin.Float) {
      _builder.setAmplitudesPreview(index, value)
    }/**
     * ```
     * Amplitude samples used to render the waveform preview in the UI.
     * ```
     *
     * `repeated float amplitudes_preview = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearAmplitudesPreview")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Float, AmplitudesPreviewProxy>.clear() {
      _builder.clearAmplitudesPreview()
    }
    /**
     * `double duration = 4;`
     */
    public var duration: kotlin.Double
      @kotlin.jvm.JvmName("getDuration")
        get() = _builder.duration
      @kotlin.jvm.JvmName("setDuration")
        set(value) {
        _builder.duration = value
      }
    /**
     * `double duration = 4;`
     */
    public fun clearDuration() {
      _builder.clearDuration()
    }

    /**
     * `string media_type = 5;`
     */
    public var mediaType: kotlin.String
      @kotlin.jvm.JvmName("getMediaType")
        get() = _builder.mediaType
      @kotlin.jvm.JvmName("setMediaType")
        set(value) {
        _builder.mediaType = value
      }
    /**
     * `string media_type = 5;`
     */
    public fun clearMediaType() {
      _builder.clearMediaType()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageStatus status = 6;`
     */
    public var status: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageStatus status = 6;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageRole role = 7;`
     */
    public var role: yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.MessageRole
      @kotlin.jvm.JvmName("getRole")
        get() = _builder.role
      @kotlin.jvm.JvmName("setRole")
        set(value) {
        _builder.role = value
      }
    public var roleValue: kotlin.Int
      @kotlin.jvm.JvmName("getRoleValue")
        get() = _builder.roleValue
      @kotlin.jvm.JvmName("setRoleValue")
        set(value) {
        _builder.roleValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v1.MessageRole role = 7;`
     */
    public fun clearRole() {
      _builder.clearRole()
    }

    /**
     * `int64 byte_count = 8;`
     */
    public var byteCount: kotlin.Long
      @kotlin.jvm.JvmName("getByteCount")
        get() = _builder.byteCount
      @kotlin.jvm.JvmName("setByteCount")
        set(value) {
        _builder.byteCount = value
      }
    /**
     * `int64 byte_count = 8;`
     */
    public fun clearByteCount() {
      _builder.clearByteCount()
    }

    /**
     * `string file_name = 9;`
     */
    public var fileName: kotlin.String
      @kotlin.jvm.JvmName("getFileName")
        get() = _builder.fileName
      @kotlin.jvm.JvmName("setFileName")
        set(value) {
        _builder.fileName = value
      }
    /**
     * `string file_name = 9;`
     */
    public fun clearFileName() {
      _builder.clearFileName()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessage.copy(block: `yalo.external_channel.in_app.sdk.v1`.VoiceMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessage =
  `yalo.external_channel.in_app.sdk.v1`.VoiceMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v1.SdkMessageOuterClass.VoiceMessageOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

