// Copyright (c) Yalochat, Inc. All rights reserved.

export {
  protobufPackage,
  // Enums
  ResponseStatus,
  MessageRole,
  MessageStatus,
  ProductMessageRequest_Orientation,
  // Enum helpers
  responseStatusFromJSON,
  responseStatusToJSON,
  messageRoleFromJSON,
  messageRoleToJSON,
  messageStatusFromJSON,
  messageStatusToJSON,
  productMessageRequest_OrientationFromJSON,
  productMessageRequest_OrientationToJSON,
  // Message codecs
  SdkMessage,
  TextMessage,
  TextMessageRequest,
  TextMessageResponse,
  VoiceMessage,
  VoiceMessageRequest,
  VoiceMessageResponse,
  ImageMessage,
  ImageMessageRequest,
  ImageMessageResponse,
  MessageReceiptRequest,
  MessageReceiptResponse,
  AddToCartRequest,
  AddToCartResponse,
  RemoveFromCartRequest,
  RemoveFromCartResponse,
  ClearCartRequest,
  ClearCartResponse,
  GuidanceCardRequest,
  GuidanceCardResponse,
  AddPromotionRequest,
  AddPromotionResponse,
  PromotionMessageRequest,
  PromotionMessageResponse,
  Product,
  ProductMessageRequest,
  ProductMessageResponse,
  ChatStatusRequest,
  ChatStatusResponse,
  CustomActionRequest,
  CustomActionResponse,
} from './sdk_message';

export type {
  MessageFns,
  DeepPartial,
  Exact,
  // Interface types (same name as codec consts — re-exported as types)
  SdkMessage as SdkMessageType,
  TextMessage as TextMessageType,
  TextMessageRequest as TextMessageRequestType,
  TextMessageResponse as TextMessageResponseType,
  VoiceMessage as VoiceMessageType,
  VoiceMessageRequest as VoiceMessageRequestType,
  VoiceMessageResponse as VoiceMessageResponseType,
  ImageMessage as ImageMessageType,
  ImageMessageRequest as ImageMessageRequestType,
  ImageMessageResponse as ImageMessageResponseType,
  MessageReceiptRequest as MessageReceiptRequestType,
  MessageReceiptResponse as MessageReceiptResponseType,
  AddToCartRequest as AddToCartRequestType,
  AddToCartResponse as AddToCartResponseType,
  RemoveFromCartRequest as RemoveFromCartRequestType,
  RemoveFromCartResponse as RemoveFromCartResponseType,
  ClearCartRequest as ClearCartRequestType,
  ClearCartResponse as ClearCartResponseType,
  GuidanceCardRequest as GuidanceCardRequestType,
  GuidanceCardResponse as GuidanceCardResponseType,
  AddPromotionRequest as AddPromotionRequestType,
  AddPromotionResponse as AddPromotionResponseType,
  PromotionMessageRequest as PromotionMessageRequestType,
  PromotionMessageResponse as PromotionMessageResponseType,
  Product as ProductType,
  ProductMessageRequest as ProductMessageRequestType,
  ProductMessageResponse as ProductMessageResponseType,
  ChatStatusRequest as ChatStatusRequestType,
  ChatStatusResponse as ChatStatusResponseType,
  CustomActionRequest as CustomActionRequestType,
  CustomActionResponse as CustomActionResponseType,
} from './sdk_message';
