// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializeaddPromotionRequest")
public inline fun addPromotionRequest(block: yalo.external_channel.in_app.sdk.v2.AddPromotionRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AddPromotionRequest =
  yalo.external_channel.in_app.sdk.v2.AddPromotionRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AddPromotionRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * AddPromotionRequest asks the channel to apply a promotion to the active cart.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.AddPromotionRequest`
 */
public object AddPromotionRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AddPromotionRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AddPromotionRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AddPromotionRequest = _builder.build()

    /**
     * `string promotion_id = 1;`
     */
    public var promotionId: kotlin.String
      @kotlin.jvm.JvmName("getPromotionId")
        get() = _builder.promotionId
      @kotlin.jvm.JvmName("setPromotionId")
        set(value) {
        _builder.promotionId = value
      }
    /**
     * `string promotion_id = 1;`
     */
    public fun clearPromotionId() {
      _builder.clearPromotionId()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val AddPromotionRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AddPromotionRequest.copy(block: `yalo.external_channel.in_app.sdk.v2`.AddPromotionRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AddPromotionRequest =
  `yalo.external_channel.in_app.sdk.v2`.AddPromotionRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AddPromotionRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

