// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializeauthResponse")
public inline fun authResponse(block: yalo.external_channel.in_app.sdk.v2.AuthResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AuthResponse =
  yalo.external_channel.in_app.sdk.v2.AuthResponseKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AuthResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * AuthResponse is returned by both POST /auth and POST /oauth/token.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.AuthResponse`
 */
public object AuthResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AuthResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AuthResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AuthResponse = _builder.build()

    /**
     * `string access_token = 1;`
     */
    public var accessToken: kotlin.String
      @kotlin.jvm.JvmName("getAccessToken")
        get() = _builder.accessToken
      @kotlin.jvm.JvmName("setAccessToken")
        set(value) {
        _builder.accessToken = value
      }
    /**
     * `string access_token = 1;`
     */
    public fun clearAccessToken() {
      _builder.clearAccessToken()
    }

    /**
     * `string token_type = 2;`
     */
    public var tokenType: kotlin.String
      @kotlin.jvm.JvmName("getTokenType")
        get() = _builder.tokenType
      @kotlin.jvm.JvmName("setTokenType")
        set(value) {
        _builder.tokenType = value
      }
    /**
     * `string token_type = 2;`
     */
    public fun clearTokenType() {
      _builder.clearTokenType()
    }

    /**
     * `int64 expires_in = 3;`
     */
    public var expiresIn: kotlin.Long
      @kotlin.jvm.JvmName("getExpiresIn")
        get() = _builder.expiresIn
      @kotlin.jvm.JvmName("setExpiresIn")
        set(value) {
        _builder.expiresIn = value
      }
    /**
     * `int64 expires_in = 3;`
     */
    public fun clearExpiresIn() {
      _builder.clearExpiresIn()
    }

    /**
     * `string refresh_token = 4;`
     */
    public var refreshToken: kotlin.String
      @kotlin.jvm.JvmName("getRefreshToken")
        get() = _builder.refreshToken
      @kotlin.jvm.JvmName("setRefreshToken")
        set(value) {
        _builder.refreshToken = value
      }
    /**
     * `string refresh_token = 4;`
     */
    public fun clearRefreshToken() {
      _builder.clearRefreshToken()
    }

    /**
     * `string client_id = 5;`
     */
    public var clientId: kotlin.String
      @kotlin.jvm.JvmName("getClientId")
        get() = _builder.clientId
      @kotlin.jvm.JvmName("setClientId")
        set(value) {
        _builder.clientId = value
      }
    /**
     * `string client_id = 5;`
     */
    public fun clearClientId() {
      _builder.clearClientId()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AuthResponse.copy(block: `yalo.external_channel.in_app.sdk.v2`.AuthResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.AuthResponse =
  `yalo.external_channel.in_app.sdk.v2`.AuthResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

