// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializeclearCartRequest")
public inline fun clearCartRequest(block: yalo.external_channel.in_app.sdk.v2.ClearCartRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ClearCartRequest =
  yalo.external_channel.in_app.sdk.v2.ClearCartRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ClearCartRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * ClearCartRequest asks the channel to empty the active cart entirely.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.ClearCartRequest`
 */
public object ClearCartRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ClearCartRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ClearCartRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ClearCartRequest = _builder.build()

    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ClearCartRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ClearCartRequest.copy(block: `yalo.external_channel.in_app.sdk.v2`.ClearCartRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ClearCartRequest =
  `yalo.external_channel.in_app.sdk.v2`.ClearCartRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ClearCartRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

