// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializeconnectionAck")
public inline fun connectionAck(block: yalo.external_channel.in_app.sdk.v2.ConnectionAckKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ConnectionAck =
  yalo.external_channel.in_app.sdk.v2.ConnectionAckKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ConnectionAck.newBuilder()).apply { block() }._build()
/**
 * ```
 * ConnectionAck is the first frame the server sends after accepting the
 * WebSocket upgrade. Clients must wait for it before flushing any buffered
 * SdkMessage frames and may use connection_id to correlate server-side logs.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.ConnectionAck`
 */
public object ConnectionAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ConnectionAck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ConnectionAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ConnectionAck = _builder.build()

    /**
     * ```
     * Constant discriminator; always CONNECTION_ACK_TYPE_CONNECTION_ACK.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.ConnectionAckType type = 1;`
     */
    public var type: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ConnectionAckType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * ```
     * Constant discriminator; always CONNECTION_ACK_TYPE_CONNECTION_ACK.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.ConnectionAckType type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `string connection_id = 2;`
     */
    public var connectionId: kotlin.String
      @kotlin.jvm.JvmName("getConnectionId")
        get() = _builder.connectionId
      @kotlin.jvm.JvmName("setConnectionId")
        set(value) {
        _builder.connectionId = value
      }
    /**
     * `string connection_id = 2;`
     */
    public fun clearConnectionId() {
      _builder.clearConnectionId()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ConnectionAckKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ConnectionAck.copy(block: `yalo.external_channel.in_app.sdk.v2`.ConnectionAckKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ConnectionAck =
  `yalo.external_channel.in_app.sdk.v2`.ConnectionAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ConnectionAckOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

