// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializegetCommandsResponse")
public inline fun getCommandsResponse(block: yalo.external_channel.in_app.sdk.v2.GetCommandsResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCommandsResponse =
  yalo.external_channel.in_app.sdk.v2.GetCommandsResponseKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCommandsResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * GetCommandsResponse declares which commands the SDK is able to execute,
 * so the channel can decide which ones it may dispatch back to the client.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.GetCommandsResponse`
 */
public object GetCommandsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCommandsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCommandsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCommandsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class CommandsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .yalo.external_channel.in_app.sdk.v2.SdkCommand commands = 1;`
     */
     public val commands: com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand, CommandsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.commandsList
      )
    /**
     * `repeated .yalo.external_channel.in_app.sdk.v2.SdkCommand commands = 1;`
     * @param value The commands to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addCommands")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand, CommandsProxy>.add(value: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand) {
      _builder.addCommands(value)
    }/**
     * `repeated .yalo.external_channel.in_app.sdk.v2.SdkCommand commands = 1;`
     * @param value The commands to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignCommands")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand, CommandsProxy>.plusAssign(value: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand) {
      add(value)
    }/**
     * `repeated .yalo.external_channel.in_app.sdk.v2.SdkCommand commands = 1;`
     * @param values The commands to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllCommands")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand, CommandsProxy>.addAll(values: kotlin.collections.Iterable<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand>) {
      _builder.addAllCommands(values)
    }/**
     * `repeated .yalo.external_channel.in_app.sdk.v2.SdkCommand commands = 1;`
     * @param values The commands to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllCommands")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand, CommandsProxy>.plusAssign(values: kotlin.collections.Iterable<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand>) {
      addAll(values)
    }/**
     * `repeated .yalo.external_channel.in_app.sdk.v2.SdkCommand commands = 1;`
     * @param index The index to set the value at.
     * @param value The commands to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setCommands")
    public operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand, CommandsProxy>.set(index: kotlin.Int, value: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand) {
      _builder.setCommands(index, value)
    }/**
     * `repeated .yalo.external_channel.in_app.sdk.v2.SdkCommand commands = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearCommands")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkCommand, CommandsProxy>.clear() {
      _builder.clearCommands()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val GetCommandsResponseKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCommandsResponse.copy(block: `yalo.external_channel.in_app.sdk.v2`.GetCommandsResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCommandsResponse =
  `yalo.external_channel.in_app.sdk.v2`.GetCommandsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCommandsResponseOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

