// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializegetCartRequest")
public inline fun getCartRequest(block: yalo.external_channel.in_app.sdk.v2.GetCartRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartRequest =
  yalo.external_channel.in_app.sdk.v2.GetCartRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * GetCartRequest asks the channel to return the products in the active cart,
 * one page at a time. Omit cursor to fetch the first page.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.GetCartRequest`
 */
public object GetCartRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartRequest = _builder.build()

    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val GetCartRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * ```
     * Cursor identifying the page to fetch. Omit to fetch the first page.
     * ```
     *
     * `optional string cursor = 2;`
     */
    public var cursor: kotlin.String
      @kotlin.jvm.JvmName("getCursor")
        get() = _builder.cursor
      @kotlin.jvm.JvmName("setCursor")
        set(value) {
        _builder.cursor = value
      }
    /**
     * ```
     * Cursor identifying the page to fetch. Omit to fetch the first page.
     * ```
     *
     * `optional string cursor = 2;`
     */
    public fun clearCursor() {
      _builder.clearCursor()
    }
    /**
     * ```
     * Cursor identifying the page to fetch. Omit to fetch the first page.
     * ```
     *
     * `optional string cursor = 2;`
     * @return Whether the cursor field is set.
     */
    public fun hasCursor(): kotlin.Boolean {
      return _builder.hasCursor()
    }

    /**
     * ```
     * Maximum number of products to return in the page. When omitted the
     * channel applies its own default page size.
     * ```
     *
     * `optional int32 page_size = 3;`
     */
    public var pageSize: kotlin.Int
      @kotlin.jvm.JvmName("getPageSize")
        get() = _builder.pageSize
      @kotlin.jvm.JvmName("setPageSize")
        set(value) {
        _builder.pageSize = value
      }
    /**
     * ```
     * Maximum number of products to return in the page. When omitted the
     * channel applies its own default page size.
     * ```
     *
     * `optional int32 page_size = 3;`
     */
    public fun clearPageSize() {
      _builder.clearPageSize()
    }
    /**
     * ```
     * Maximum number of products to return in the page. When omitted the
     * channel applies its own default page size.
     * ```
     *
     * `optional int32 page_size = 3;`
     * @return Whether the pageSize field is set.
     */
    public fun hasPageSize(): kotlin.Boolean {
      return _builder.hasPageSize()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartRequest.copy(block: `yalo.external_channel.in_app.sdk.v2`.GetCartRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartRequest =
  `yalo.external_channel.in_app.sdk.v2`.GetCartRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

