// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializegetCartResponse")
public inline fun getCartResponse(block: yalo.external_channel.in_app.sdk.v2.GetCartResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartResponse =
  yalo.external_channel.in_app.sdk.v2.GetCartResponseKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * GetCartResponse returns a single page of products from the active cart.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.GetCartResponse`
 */
public object GetCartResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartResponse = _builder.build()

    /**
     * `.yalo.external_channel.in_app.sdk.v2.ResponseStatus status = 1;`
     */
    public var status: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ResponseStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v2.ResponseStatus status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val GetCartResponseKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ProductsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Products contained in this page of the cart.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v2.Product products = 3;`
     */
     public val products: com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product, ProductsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.productsList
      )
    /**
     * ```
     * Products contained in this page of the cart.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v2.Product products = 3;`
     * @param value The products to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addProducts")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product, ProductsProxy>.add(value: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product) {
      _builder.addProducts(value)
    }
    /**
     * ```
     * Products contained in this page of the cart.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v2.Product products = 3;`
     * @param value The products to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignProducts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product, ProductsProxy>.plusAssign(value: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product) {
      add(value)
    }
    /**
     * ```
     * Products contained in this page of the cart.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v2.Product products = 3;`
     * @param values The products to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllProducts")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product, ProductsProxy>.addAll(values: kotlin.collections.Iterable<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product>) {
      _builder.addAllProducts(values)
    }
    /**
     * ```
     * Products contained in this page of the cart.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v2.Product products = 3;`
     * @param values The products to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllProducts")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product, ProductsProxy>.plusAssign(values: kotlin.collections.Iterable<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product>) {
      addAll(values)
    }
    /**
     * ```
     * Products contained in this page of the cart.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v2.Product products = 3;`
     * @param index The index to set the value at.
     * @param value The products to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setProducts")
    public operator fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product, ProductsProxy>.set(index: kotlin.Int, value: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product) {
      _builder.setProducts(index, value)
    }
    /**
     * ```
     * Products contained in this page of the cart.
     * ```
     *
     * `repeated .yalo.external_channel.in_app.sdk.v2.Product products = 3;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearProducts")
    public fun com.google.protobuf.kotlin.DslList<yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product, ProductsProxy>.clear() {
      _builder.clearProducts()
    }

    /**
     * ```
     * Cursor-based pagination metadata describing this page and how to fetch
     * adjacent ones.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.PageInfo page_info = 4;`
     */
    public var pageInfo: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo
      @kotlin.jvm.JvmName("getPageInfo")
        get() = _builder.pageInfo
      @kotlin.jvm.JvmName("setPageInfo")
        set(value) {
        _builder.pageInfo = value
      }
    /**
     * ```
     * Cursor-based pagination metadata describing this page and how to fetch
     * adjacent ones.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.PageInfo page_info = 4;`
     */
    public fun clearPageInfo() {
      _builder.clearPageInfo()
    }
    /**
     * ```
     * Cursor-based pagination metadata describing this page and how to fetch
     * adjacent ones.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.PageInfo page_info = 4;`
     * @return Whether the pageInfo field is set.
     */
    public fun hasPageInfo(): kotlin.Boolean {
      return _builder.hasPageInfo()
    }

    public val GetCartResponseKt.Dsl.pageInfoOrNull: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo?
      get() = _builder.pageInfoOrNull
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartResponse.copy(block: `yalo.external_channel.in_app.sdk.v2`.GetCartResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartResponse =
  `yalo.external_channel.in_app.sdk.v2`.GetCartResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartResponseOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GetCartResponseOrBuilder.pageInfoOrNull: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo?
  get() = if (hasPageInfo()) getPageInfo() else null

