// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializeguidanceCardResponse")
public inline fun guidanceCardResponse(block: yalo.external_channel.in_app.sdk.v2.GuidanceCardResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GuidanceCardResponse =
  yalo.external_channel.in_app.sdk.v2.GuidanceCardResponseKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GuidanceCardResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * GuidanceCardResponse returns the guidance cards to display to the user.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.GuidanceCardResponse`
 */
public object GuidanceCardResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GuidanceCardResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GuidanceCardResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GuidanceCardResponse = _builder.build()

    /**
     * `.yalo.external_channel.in_app.sdk.v2.ResponseStatus status = 1;`
     */
    public var status: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ResponseStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v2.ResponseStatus status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val GuidanceCardResponseKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * `string guidance_title = 3;`
     */
    public var guidanceTitle: kotlin.String
      @kotlin.jvm.JvmName("getGuidanceTitle")
        get() = _builder.guidanceTitle
      @kotlin.jvm.JvmName("setGuidanceTitle")
        set(value) {
        _builder.guidanceTitle = value
      }
    /**
     * `string guidance_title = 3;`
     */
    public fun clearGuidanceTitle() {
      _builder.clearGuidanceTitle()
    }

    /**
     * `string guidance_description = 4;`
     */
    public var guidanceDescription: kotlin.String
      @kotlin.jvm.JvmName("getGuidanceDescription")
        get() = _builder.guidanceDescription
      @kotlin.jvm.JvmName("setGuidanceDescription")
        set(value) {
        _builder.guidanceDescription = value
      }
    /**
     * `string guidance_description = 4;`
     */
    public fun clearGuidanceDescription() {
      _builder.clearGuidanceDescription()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class GuidanceCardsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string guidance_cards = 5;`
     * @return A list containing the guidanceCards.
     */
    public val guidanceCards: com.google.protobuf.kotlin.DslList<kotlin.String, GuidanceCardsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.guidanceCardsList
      )
    /**
     * `repeated string guidance_cards = 5;`
     * @param value The guidanceCards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addGuidanceCards")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, GuidanceCardsProxy>.add(value: kotlin.String) {
      _builder.addGuidanceCards(value)
    }
    /**
     * `repeated string guidance_cards = 5;`
     * @param value The guidanceCards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignGuidanceCards")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, GuidanceCardsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string guidance_cards = 5;`
     * @param values The guidanceCards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllGuidanceCards")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, GuidanceCardsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllGuidanceCards(values)
    }
    /**
     * `repeated string guidance_cards = 5;`
     * @param values The guidanceCards to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllGuidanceCards")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, GuidanceCardsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string guidance_cards = 5;`
     * @param index The index to set the value at.
     * @param value The guidanceCards to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setGuidanceCards")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, GuidanceCardsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setGuidanceCards(index, value)
    }/**
     * `repeated string guidance_cards = 5;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setGuidanceCards")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, GuidanceCardsProxy>.clear() {
      _builder.clearGuidanceCards()
    }}
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GuidanceCardResponse.copy(block: `yalo.external_channel.in_app.sdk.v2`.GuidanceCardResponseKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GuidanceCardResponse =
  `yalo.external_channel.in_app.sdk.v2`.GuidanceCardResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.GuidanceCardResponseOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

