// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializepageInfo")
public inline fun pageInfo(block: yalo.external_channel.in_app.sdk.v2.PageInfoKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo =
  yalo.external_channel.in_app.sdk.v2.PageInfoKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo.newBuilder()).apply { block() }._build()
/**
 * ```
 * PageInfo carries cursor-based pagination metadata for a page of results.
 * All cursor and count fields are optional so a source may expose only the
 * subset it can compute (e.g. cursors without a known total). Cursors are
 * opaque string tokens: numeric channels stringify their offset, token-based
 * channels send the token verbatim, and the client passes them back unchanged.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.PageInfo`
 */
public object PageInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo = _builder.build()

    /**
     * ```
     * Total number of items across all pages, when known.
     * ```
     *
     * `optional int32 total = 1;`
     */
    public var total: kotlin.Int
      @kotlin.jvm.JvmName("getTotal")
        get() = _builder.total
      @kotlin.jvm.JvmName("setTotal")
        set(value) {
        _builder.total = value
      }
    /**
     * ```
     * Total number of items across all pages, when known.
     * ```
     *
     * `optional int32 total = 1;`
     */
    public fun clearTotal() {
      _builder.clearTotal()
    }
    /**
     * ```
     * Total number of items across all pages, when known.
     * ```
     *
     * `optional int32 total = 1;`
     * @return Whether the total field is set.
     */
    public fun hasTotal(): kotlin.Boolean {
      return _builder.hasTotal()
    }

    /**
     * ```
     * Total number of pages across the full result set, when known.
     * ```
     *
     * `optional int32 total_pages = 2;`
     */
    public var totalPages: kotlin.Int
      @kotlin.jvm.JvmName("getTotalPages")
        get() = _builder.totalPages
      @kotlin.jvm.JvmName("setTotalPages")
        set(value) {
        _builder.totalPages = value
      }
    /**
     * ```
     * Total number of pages across the full result set, when known.
     * ```
     *
     * `optional int32 total_pages = 2;`
     */
    public fun clearTotalPages() {
      _builder.clearTotalPages()
    }
    /**
     * ```
     * Total number of pages across the full result set, when known.
     * ```
     *
     * `optional int32 total_pages = 2;`
     * @return Whether the totalPages field is set.
     */
    public fun hasTotalPages(): kotlin.Boolean {
      return _builder.hasTotalPages()
    }

    /**
     * ```
     * Current page index, when the source paginates by page number.
     * ```
     *
     * `optional int32 page = 3;`
     */
    public var page: kotlin.Int
      @kotlin.jvm.JvmName("getPage")
        get() = _builder.page
      @kotlin.jvm.JvmName("setPage")
        set(value) {
        _builder.page = value
      }
    /**
     * ```
     * Current page index, when the source paginates by page number.
     * ```
     *
     * `optional int32 page = 3;`
     */
    public fun clearPage() {
      _builder.clearPage()
    }
    /**
     * ```
     * Current page index, when the source paginates by page number.
     * ```
     *
     * `optional int32 page = 3;`
     * @return Whether the page field is set.
     */
    public fun hasPage(): kotlin.Boolean {
      return _builder.hasPage()
    }

    /**
     * ```
     * Cursor that produced the current page.
     * ```
     *
     * `optional string cursor = 4;`
     */
    public var cursor: kotlin.String
      @kotlin.jvm.JvmName("getCursor")
        get() = _builder.cursor
      @kotlin.jvm.JvmName("setCursor")
        set(value) {
        _builder.cursor = value
      }
    /**
     * ```
     * Cursor that produced the current page.
     * ```
     *
     * `optional string cursor = 4;`
     */
    public fun clearCursor() {
      _builder.clearCursor()
    }
    /**
     * ```
     * Cursor that produced the current page.
     * ```
     *
     * `optional string cursor = 4;`
     * @return Whether the cursor field is set.
     */
    public fun hasCursor(): kotlin.Boolean {
      return _builder.hasCursor()
    }

    /**
     * ```
     * Cursor to pass in the next request to fetch the following page.
     * Absent when the current page is the last one.
     * ```
     *
     * `optional string next_cursor = 5;`
     */
    public var nextCursor: kotlin.String
      @kotlin.jvm.JvmName("getNextCursor")
        get() = _builder.nextCursor
      @kotlin.jvm.JvmName("setNextCursor")
        set(value) {
        _builder.nextCursor = value
      }
    /**
     * ```
     * Cursor to pass in the next request to fetch the following page.
     * Absent when the current page is the last one.
     * ```
     *
     * `optional string next_cursor = 5;`
     */
    public fun clearNextCursor() {
      _builder.clearNextCursor()
    }
    /**
     * ```
     * Cursor to pass in the next request to fetch the following page.
     * Absent when the current page is the last one.
     * ```
     *
     * `optional string next_cursor = 5;`
     * @return Whether the nextCursor field is set.
     */
    public fun hasNextCursor(): kotlin.Boolean {
      return _builder.hasNextCursor()
    }

    /**
     * ```
     * Cursor to pass to fetch the previous page. Absent on the first page.
     * ```
     *
     * `optional string prev_cursor = 6;`
     */
    public var prevCursor: kotlin.String
      @kotlin.jvm.JvmName("getPrevCursor")
        get() = _builder.prevCursor
      @kotlin.jvm.JvmName("setPrevCursor")
        set(value) {
        _builder.prevCursor = value
      }
    /**
     * ```
     * Cursor to pass to fetch the previous page. Absent on the first page.
     * ```
     *
     * `optional string prev_cursor = 6;`
     */
    public fun clearPrevCursor() {
      _builder.clearPrevCursor()
    }
    /**
     * ```
     * Cursor to pass to fetch the previous page. Absent on the first page.
     * ```
     *
     * `optional string prev_cursor = 6;`
     * @return Whether the prevCursor field is set.
     */
    public fun hasPrevCursor(): kotlin.Boolean {
      return _builder.hasPrevCursor()
    }

    /**
     * ```
     * Number of items requested per page.
     * ```
     *
     * `int32 page_size = 7;`
     */
    public var pageSize: kotlin.Int
      @kotlin.jvm.JvmName("getPageSize")
        get() = _builder.pageSize
      @kotlin.jvm.JvmName("setPageSize")
        set(value) {
        _builder.pageSize = value
      }
    /**
     * ```
     * Number of items requested per page.
     * ```
     *
     * `int32 page_size = 7;`
     */
    public fun clearPageSize() {
      _builder.clearPageSize()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo.copy(block: `yalo.external_channel.in_app.sdk.v2`.PageInfoKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.PageInfo =
  `yalo.external_channel.in_app.sdk.v2`.PageInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

