// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializeproduct")
public inline fun product(block: yalo.external_channel.in_app.sdk.v2.ProductKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product =
  yalo.external_channel.in_app.sdk.v2.ProductKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product.newBuilder()).apply { block() }._build()
/**
 * ```
 * Product represents a single catalog item with pricing and quantity metadata.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.Product`
 */
public object ProductKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product = _builder.build()

    /**
     * `string sku = 1;`
     */
    public var sku: kotlin.String
      @kotlin.jvm.JvmName("getSku")
        get() = _builder.sku
      @kotlin.jvm.JvmName("setSku")
        set(value) {
        _builder.sku = value
      }
    /**
     * `string sku = 1;`
     */
    public fun clearSku() {
      _builder.clearSku()
    }

    /**
     * `string name = 2;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `double price = 3;`
     */
    public var price: kotlin.Double
      @kotlin.jvm.JvmName("getPrice")
        get() = _builder.price
      @kotlin.jvm.JvmName("setPrice")
        set(value) {
        _builder.price = value
      }
    /**
     * `double price = 3;`
     */
    public fun clearPrice() {
      _builder.clearPrice()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ImagesUrlProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string images_url = 4;`
     * @return A list containing the imagesUrl.
     */
    public val imagesUrl: com.google.protobuf.kotlin.DslList<kotlin.String, ImagesUrlProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.imagesUrlList
      )
    /**
     * `repeated string images_url = 4;`
     * @param value The imagesUrl to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addImagesUrl")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ImagesUrlProxy>.add(value: kotlin.String) {
      _builder.addImagesUrl(value)
    }
    /**
     * `repeated string images_url = 4;`
     * @param value The imagesUrl to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignImagesUrl")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ImagesUrlProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string images_url = 4;`
     * @param values The imagesUrl to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllImagesUrl")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ImagesUrlProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllImagesUrl(values)
    }
    /**
     * `repeated string images_url = 4;`
     * @param values The imagesUrl to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllImagesUrl")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ImagesUrlProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string images_url = 4;`
     * @param index The index to set the value at.
     * @param value The imagesUrl to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setImagesUrl")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ImagesUrlProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setImagesUrl(index, value)
    }/**
     * `repeated string images_url = 4;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setImagesUrl")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ImagesUrlProxy>.clear() {
      _builder.clearImagesUrl()
    }
    /**
     * ```
     * When set, sale_price takes precedence over price.
     * ```
     *
     * `optional double sale_price = 5;`
     */
    public var salePrice: kotlin.Double
      @kotlin.jvm.JvmName("getSalePrice")
        get() = _builder.salePrice
      @kotlin.jvm.JvmName("setSalePrice")
        set(value) {
        _builder.salePrice = value
      }
    /**
     * ```
     * When set, sale_price takes precedence over price.
     * ```
     *
     * `optional double sale_price = 5;`
     */
    public fun clearSalePrice() {
      _builder.clearSalePrice()
    }
    /**
     * ```
     * When set, sale_price takes precedence over price.
     * ```
     *
     * `optional double sale_price = 5;`
     * @return Whether the salePrice field is set.
     */
    public fun hasSalePrice(): kotlin.Boolean {
      return _builder.hasSalePrice()
    }

    /**
     * ```
     * Units per package (e.g. items inside a box). Used to compute quantity steps.
     * ```
     *
     * `double subunits = 6;`
     */
    public var subunits: kotlin.Double
      @kotlin.jvm.JvmName("getSubunits")
        get() = _builder.subunits
      @kotlin.jvm.JvmName("setSubunits")
        set(value) {
        _builder.subunits = value
      }
    /**
     * ```
     * Units per package (e.g. items inside a box). Used to compute quantity steps.
     * ```
     *
     * `double subunits = 6;`
     */
    public fun clearSubunits() {
      _builder.clearSubunits()
    }

    /**
     * ```
     * Increment step when adjusting primary units.
     * ```
     *
     * `double unit_step = 7;`
     */
    public var unitStep: kotlin.Double
      @kotlin.jvm.JvmName("getUnitStep")
        get() = _builder.unitStep
      @kotlin.jvm.JvmName("setUnitStep")
        set(value) {
        _builder.unitStep = value
      }
    /**
     * ```
     * Increment step when adjusting primary units.
     * ```
     *
     * `double unit_step = 7;`
     */
    public fun clearUnitStep() {
      _builder.clearUnitStep()
    }

    /**
     * ```
     * ICU message-format string for the unit name, supports plurals via {amount}.
     * e.g. "{amount, plural, one {box} other {boxes}}"
     * ```
     *
     * `string unit_name = 8;`
     */
    public var unitName: kotlin.String
      @kotlin.jvm.JvmName("getUnitName")
        get() = _builder.unitName
      @kotlin.jvm.JvmName("setUnitName")
        set(value) {
        _builder.unitName = value
      }
    /**
     * ```
     * ICU message-format string for the unit name, supports plurals via {amount}.
     * e.g. "{amount, plural, one {box} other {boxes}}"
     * ```
     *
     * `string unit_name = 8;`
     */
    public fun clearUnitName() {
      _builder.clearUnitName()
    }

    /**
     * ```
     * ICU message-format string for the subunit name, supports plurals via {amount}.
     * ```
     *
     * `optional string subunit_name = 9;`
     */
    public var subunitName: kotlin.String
      @kotlin.jvm.JvmName("getSubunitName")
        get() = _builder.subunitName
      @kotlin.jvm.JvmName("setSubunitName")
        set(value) {
        _builder.subunitName = value
      }
    /**
     * ```
     * ICU message-format string for the subunit name, supports plurals via {amount}.
     * ```
     *
     * `optional string subunit_name = 9;`
     */
    public fun clearSubunitName() {
      _builder.clearSubunitName()
    }
    /**
     * ```
     * ICU message-format string for the subunit name, supports plurals via {amount}.
     * ```
     *
     * `optional string subunit_name = 9;`
     * @return Whether the subunitName field is set.
     */
    public fun hasSubunitName(): kotlin.Boolean {
      return _builder.hasSubunitName()
    }

    /**
     * ```
     * Increment step when adjusting subunits.
     * ```
     *
     * `double subunit_step = 10;`
     */
    public var subunitStep: kotlin.Double
      @kotlin.jvm.JvmName("getSubunitStep")
        get() = _builder.subunitStep
      @kotlin.jvm.JvmName("setSubunitStep")
        set(value) {
        _builder.subunitStep = value
      }
    /**
     * ```
     * Increment step when adjusting subunits.
     * ```
     *
     * `double subunit_step = 10;`
     */
    public fun clearSubunitStep() {
      _builder.clearSubunitStep()
    }

    /**
     * `double units_added = 11;`
     */
    public var unitsAdded: kotlin.Double
      @kotlin.jvm.JvmName("getUnitsAdded")
        get() = _builder.unitsAdded
      @kotlin.jvm.JvmName("setUnitsAdded")
        set(value) {
        _builder.unitsAdded = value
      }
    /**
     * `double units_added = 11;`
     */
    public fun clearUnitsAdded() {
      _builder.clearUnitsAdded()
    }

    /**
     * `double subunits_added = 12;`
     */
    public var subunitsAdded: kotlin.Double
      @kotlin.jvm.JvmName("getSubunitsAdded")
        get() = _builder.subunitsAdded
      @kotlin.jvm.JvmName("setSubunitsAdded")
        set(value) {
        _builder.subunitsAdded = value
      }
    /**
     * `double subunits_added = 12;`
     */
    public fun clearSubunitsAdded() {
      _builder.clearSubunitsAdded()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product.copy(block: `yalo.external_channel.in_app.sdk.v2`.ProductKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Product =
  `yalo.external_channel.in_app.sdk.v2`.ProductKt.Dsl._create(this.toBuilder()).apply { block() }._build()

