// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializeproductConfirmationMessageRequest")
public inline fun productConfirmationMessageRequest(block: yalo.external_channel.in_app.sdk.v2.ProductConfirmationMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ProductConfirmationMessageRequest =
  yalo.external_channel.in_app.sdk.v2.ProductConfirmationMessageRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ProductConfirmationMessageRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * ProductConfirmationMessageRequest confirms a product cart change in the
 * client UI, identifying the affected SKU and the resulting unit/subunit
 * quantities after the operation. Display-only fields (name, price, image)
 * are resolved by the client from its own product catalog cache.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.ProductConfirmationMessageRequest`
 */
public object ProductConfirmationMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ProductConfirmationMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ProductConfirmationMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ProductConfirmationMessageRequest = _builder.build()

    /**
     * `string sku = 1;`
     */
    public var sku: kotlin.String
      @kotlin.jvm.JvmName("getSku")
        get() = _builder.sku
      @kotlin.jvm.JvmName("setSku")
        set(value) {
        _builder.sku = value
      }
    /**
     * `string sku = 1;`
     */
    public fun clearSku() {
      _builder.clearSku()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val ProductConfirmationMessageRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * ```
     * Absolute number of primary units for this SKU after the confirmed change.
     * ```
     *
     * `double units = 3;`
     */
    public var units: kotlin.Double
      @kotlin.jvm.JvmName("getUnits")
        get() = _builder.units
      @kotlin.jvm.JvmName("setUnits")
        set(value) {
        _builder.units = value
      }
    /**
     * ```
     * Absolute number of primary units for this SKU after the confirmed change.
     * ```
     *
     * `double units = 3;`
     */
    public fun clearUnits() {
      _builder.clearUnits()
    }

    /**
     * ```
     * Absolute number of subunits for this SKU after the confirmed change.
     * Omit when the product has no subunit dimension.
     * ```
     *
     * `optional double subunits = 4;`
     */
    public var subunits: kotlin.Double
      @kotlin.jvm.JvmName("getSubunits")
        get() = _builder.subunits
      @kotlin.jvm.JvmName("setSubunits")
        set(value) {
        _builder.subunits = value
      }
    /**
     * ```
     * Absolute number of subunits for this SKU after the confirmed change.
     * Omit when the product has no subunit dimension.
     * ```
     *
     * `optional double subunits = 4;`
     */
    public fun clearSubunits() {
      _builder.clearSubunits()
    }
    /**
     * ```
     * Absolute number of subunits for this SKU after the confirmed change.
     * Omit when the product has no subunit dimension.
     * ```
     *
     * `optional double subunits = 4;`
     * @return Whether the subunits field is set.
     */
    public fun hasSubunits(): kotlin.Boolean {
      return _builder.hasSubunits()
    }

    /**
     * ```
     * Structural text rendered above the confirmation card body.
     * ```
     *
     * `string header = 5;`
     */
    public var header: kotlin.String
      @kotlin.jvm.JvmName("getHeader")
        get() = _builder.header
      @kotlin.jvm.JvmName("setHeader")
        set(value) {
        _builder.header = value
      }
    /**
     * ```
     * Structural text rendered above the confirmation card body.
     * ```
     *
     * `string header = 5;`
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }

    /**
     * ```
     * Body text rendered as the main content of the confirmation card.
     * ```
     *
     * `string body = 6;`
     */
    public var body: kotlin.String
      @kotlin.jvm.JvmName("getBody")
        get() = _builder.body
      @kotlin.jvm.JvmName("setBody")
        set(value) {
        _builder.body = value
      }
    /**
     * ```
     * Body text rendered as the main content of the confirmation card.
     * ```
     *
     * `string body = 6;`
     */
    public fun clearBody() {
      _builder.clearBody()
    }

    /**
     * ```
     * Call-to-action button rendered alongside the confirmation card.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.Button button = 7;`
     */
    public var button: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Button
      @kotlin.jvm.JvmName("getButton")
        get() = _builder.button
      @kotlin.jvm.JvmName("setButton")
        set(value) {
        _builder.button = value
      }
    /**
     * ```
     * Call-to-action button rendered alongside the confirmation card.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.Button button = 7;`
     */
    public fun clearButton() {
      _builder.clearButton()
    }
    /**
     * ```
     * Call-to-action button rendered alongside the confirmation card.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.Button button = 7;`
     * @return Whether the button field is set.
     */
    public fun hasButton(): kotlin.Boolean {
      return _builder.hasButton()
    }

    public val ProductConfirmationMessageRequestKt.Dsl.buttonOrNull: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Button?
      get() = _builder.buttonOrNull

    /**
     * ```
     * Structural text rendered below the confirmation card body.
     * ```
     *
     * `string footer = 8;`
     */
    public var footer: kotlin.String
      @kotlin.jvm.JvmName("getFooter")
        get() = _builder.footer
      @kotlin.jvm.JvmName("setFooter")
        set(value) {
        _builder.footer = value
      }
    /**
     * ```
     * Structural text rendered below the confirmation card body.
     * ```
     *
     * `string footer = 8;`
     */
    public fun clearFooter() {
      _builder.clearFooter()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ProductConfirmationMessageRequest.copy(block: `yalo.external_channel.in_app.sdk.v2`.ProductConfirmationMessageRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ProductConfirmationMessageRequest =
  `yalo.external_channel.in_app.sdk.v2`.ProductConfirmationMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ProductConfirmationMessageRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.ProductConfirmationMessageRequestOrBuilder.buttonOrNull: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.Button?
  get() = if (hasButton()) getButton() else null

