// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializesdkMessageAck")
public inline fun sdkMessageAck(block: yalo.external_channel.in_app.sdk.v2.SdkMessageAckKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkMessageAck =
  yalo.external_channel.in_app.sdk.v2.SdkMessageAckKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkMessageAck.newBuilder()).apply { block() }._build()
/**
 * ```
 * SdkMessageAck is sent by the server to acknowledge receipt of a client
 * SdkMessage frame. correlation_id matches the SdkMessage.correlation_id
 * of the acknowledged frame.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.SdkMessageAck`
 */
public object SdkMessageAckKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkMessageAck.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkMessageAck.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkMessageAck = _builder.build()

    /**
     * ```
     * Constant discriminator; always SDK_MESSAGE_ACK_TYPE_MESSAGE_ACK.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.SdkMessageAckType type = 1;`
     */
    public var type: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkMessageAckType
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    public var typeValue: kotlin.Int
      @kotlin.jvm.JvmName("getTypeValue")
        get() = _builder.typeValue
      @kotlin.jvm.JvmName("setTypeValue")
        set(value) {
        _builder.typeValue = value
      }
    /**
     * ```
     * Constant discriminator; always SDK_MESSAGE_ACK_TYPE_MESSAGE_ACK.
     * ```
     *
     * `.yalo.external_channel.in_app.sdk.v2.SdkMessageAckType type = 1;`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `string correlation_id = 2;`
     */
    public var correlationId: kotlin.String
      @kotlin.jvm.JvmName("getCorrelationId")
        get() = _builder.correlationId
      @kotlin.jvm.JvmName("setCorrelationId")
        set(value) {
        _builder.correlationId = value
      }
    /**
     * `string correlation_id = 2;`
     */
    public fun clearCorrelationId() {
      _builder.clearCorrelationId()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 3;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val SdkMessageAckKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkMessageAck.copy(block: `yalo.external_channel.in_app.sdk.v2`.SdkMessageAckKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkMessageAck =
  `yalo.external_channel.in_app.sdk.v2`.SdkMessageAckKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.SdkMessageAckOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

