// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializetextMessage")
public inline fun textMessage(block: yalo.external_channel.in_app.sdk.v2.TextMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.TextMessage =
  yalo.external_channel.in_app.sdk.v2.TextMessageKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.TextMessage.newBuilder()).apply { block() }._build()
/**
 * ```
 * TextMessage holds the payload of a plain-text conversation turn.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.TextMessage`
 */
public object TextMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.TextMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.TextMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.TextMessage = _builder.build()

    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 1;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val TextMessageKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * `string text = 2;`
     */
    public var text: kotlin.String
      @kotlin.jvm.JvmName("getText")
        get() = _builder.text
      @kotlin.jvm.JvmName("setText")
        set(value) {
        _builder.text = value
      }
    /**
     * `string text = 2;`
     */
    public fun clearText() {
      _builder.clearText()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v2.MessageStatus status = 3;`
     */
    public var status: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.MessageStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v2.MessageStatus status = 3;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `.yalo.external_channel.in_app.sdk.v2.MessageRole role = 4;`
     */
    public var role: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.MessageRole
      @kotlin.jvm.JvmName("getRole")
        get() = _builder.role
      @kotlin.jvm.JvmName("setRole")
        set(value) {
        _builder.role = value
      }
    public var roleValue: kotlin.Int
      @kotlin.jvm.JvmName("getRoleValue")
        get() = _builder.roleValue
      @kotlin.jvm.JvmName("setRoleValue")
        set(value) {
        _builder.roleValue = value
      }
    /**
     * `.yalo.external_channel.in_app.sdk.v2.MessageRole role = 4;`
     */
    public fun clearRole() {
      _builder.clearRole()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.TextMessage.copy(block: `yalo.external_channel.in_app.sdk.v2`.TextMessageKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.TextMessage =
  `yalo.external_channel.in_app.sdk.v2`.TextMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.TextMessageOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

