// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: events/external_channel/in_app/sdk/sdk_message.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package yalo.external_channel.in_app.sdk.v2;

@kotlin.jvm.JvmName("-initializeupdateCartProductRequest")
public inline fun updateCartProductRequest(block: yalo.external_channel.in_app.sdk.v2.UpdateCartProductRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.UpdateCartProductRequest =
  yalo.external_channel.in_app.sdk.v2.UpdateCartProductRequestKt.Dsl._create(yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.UpdateCartProductRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * UpdateCartProductRequest sets the absolute quantities for a SKU in the
 * active cart, replacing whatever was there before. It is intended to
 * supersede AddToCartRequest / RemoveFromCartRequest so the channel does
 * not need to reconcile incremental deltas.
 *
 * Semantics:
 * - units = 0 and subunits absent (or 0) removes the SKU from the cart.
 * - subunits is omitted for products that do not expose a subunit dimension.
 * ```
 *
 * Protobuf type `yalo.external_channel.in_app.sdk.v2.UpdateCartProductRequest`
 */
public object UpdateCartProductRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.UpdateCartProductRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.UpdateCartProductRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.UpdateCartProductRequest = _builder.build()

    /**
     * `string sku = 1;`
     */
    public var sku: kotlin.String
      @kotlin.jvm.JvmName("getSku")
        get() = _builder.sku
      @kotlin.jvm.JvmName("setSku")
        set(value) {
        _builder.sku = value
      }
    /**
     * `string sku = 1;`
     */
    public fun clearSku() {
      _builder.clearSku()
    }

    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public var timestamp: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
    /**
     * `.google.protobuf.Timestamp timestamp = 2;`
     * @return Whether the timestamp field is set.
     */
    public fun hasTimestamp(): kotlin.Boolean {
      return _builder.hasTimestamp()
    }

    public val UpdateCartProductRequestKt.Dsl.timestampOrNull: com.google.protobuf.Timestamp?
      get() = _builder.timestampOrNull

    /**
     * ```
     * Absolute number of primary units for this SKU after the update.
     * ```
     *
     * `double units = 3;`
     */
    public var units: kotlin.Double
      @kotlin.jvm.JvmName("getUnits")
        get() = _builder.units
      @kotlin.jvm.JvmName("setUnits")
        set(value) {
        _builder.units = value
      }
    /**
     * ```
     * Absolute number of primary units for this SKU after the update.
     * ```
     *
     * `double units = 3;`
     */
    public fun clearUnits() {
      _builder.clearUnits()
    }

    /**
     * ```
     * Absolute number of subunits for this SKU after the update. Omit when
     * the product has no subunit dimension.
     * ```
     *
     * `optional double subunits = 4;`
     */
    public var subunits: kotlin.Double
      @kotlin.jvm.JvmName("getSubunits")
        get() = _builder.subunits
      @kotlin.jvm.JvmName("setSubunits")
        set(value) {
        _builder.subunits = value
      }
    /**
     * ```
     * Absolute number of subunits for this SKU after the update. Omit when
     * the product has no subunit dimension.
     * ```
     *
     * `optional double subunits = 4;`
     */
    public fun clearSubunits() {
      _builder.clearSubunits()
    }
    /**
     * ```
     * Absolute number of subunits for this SKU after the update. Omit when
     * the product has no subunit dimension.
     * ```
     *
     * `optional double subunits = 4;`
     * @return Whether the subunits field is set.
     */
    public fun hasSubunits(): kotlin.Boolean {
      return _builder.hasSubunits()
    }
  }
}
public inline fun yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.UpdateCartProductRequest.copy(block: `yalo.external_channel.in_app.sdk.v2`.UpdateCartProductRequestKt.Dsl.() -> kotlin.Unit): yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.UpdateCartProductRequest =
  `yalo.external_channel.in_app.sdk.v2`.UpdateCartProductRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val yalo.external_channel.in_app.sdk.v2.SdkMessageOuterClass.UpdateCartProductRequestOrBuilder.timestampOrNull: com.google.protobuf.Timestamp?
  get() = if (hasTimestamp()) getTimestamp() else null

